### ISSUE TITLE
Support windows as target platform

### ISSUE THREAD

**Issue by lb1a** [openpaperwork/paperwork#311]
Hello,
i use mainly Linux but also have windows on some boxes and i would like to use paperwork there as well. I was wondering if this is possible? There seems to be no documentation about windows at all :cry: 

All the required tools are met on windows as well:
Sane - http://www.xsane.org/xsane-win32.html
GTK+ - http://www.gtk.org/download/index.php
Tesseract - https://code.google.com/p/tesseract-ocr/#Supported_Platforms
whoosh - python -> platform independant

Did you had windows in mind while developing paperwork? Or should i just try it and see if i can work it out somehow?

**Comment by jflesch** [comment]
Sorry, I lost this ticket so I forgot to update it. Anyway, I've decided I'll work on a Windows version, *however*, I'll try to monetize it (see #488 and https://openpaper.work/ for details).
