### ISSUE TITLE
Missing paperwork icon on toolbar and about dialog

### ISSUE THREAD

**Issue by plietar** [openpaperwork/paperwork#319]
Hi,
When running paperwork, both stable and testing versions, the icon is missing on the scan button and on the about dialog.
The console shows : 

```
(paperwork:32): Gtk-WARNING **: Could not load image 'paperwork.svg': Failed to open file '/usr/share/paperwork/mainwindow/paperwork.svg': No such file or directory
(paperwork:32): Gtk-WARNING **: Could not load image 'paperwork.svg': Failed to open file '/usr/share/paperwork/aboutdialog/paperwork.svg': No such file or directory
```

The only `paperwork.svg` file installed is in `/usr/share/icons/paperwork.svg`, as defined in [setup.py](https://github.com/jflesch/paperwork/blob/testing/setup.py#L170-L171).

I have no experience at all with glade, so I don't know how to change it's search path. The icon seems to be looked up relatively to the glade file.

Thanks

**Comment by tiramiseb** [comment]
I have the same issue on Kubuntu 16.10, with Paperwork, 1.0.1.
![](https://cloud.githubusercontent.com/assets/1292007/20249246/a37612ba-a9f5-11e6-984e-c6cea2ce26c7.png)

**Comment by jflesch** [comment]
I've added extra icons in Paperwork 1.0.2 that may fix this issue. Can you give it a try please ?
