### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#480]
(Suggested by Jocelyn Aznar)

A progression indicator (+ extra buttons) for the search could be handy. It would tell the user if it has missed a match for a keyword, or if they have seen them all.

**Comment by mjourdan** [comment]
Please find [a mockup](https://github.com/mjourdan/gnome-design/blob/master/paperwork/experiments/find.png) which aims to achieve #80 also. Comments are welcome.

**Comment by jflesch** [comment]
Looks good to me. I'm just wondering why are they 2 colors in the progressbar, and in your example shouldn't it be to 50% ?

**Comment by mjourdan** [comment]
Le 2016-09-04 13:04, Jerome Flesch a écrit :
> Looks good to me. I'm just wondering why are they 2 colors in the
> progressbar, and in your example shouldn't it be to 50% ?

Very valid questions. My idea was the "1st of 2 occurrences" relates to 
the current document, while the progress bar relates to the total number 
of occurences accross all documents. In our example, we have 12,5% 
(strong blue) for the currently selected occurence, we have 25% filled 
(light blue) for the currently highlighted occurences. The rest (gray) 
is for about 6 occurrences left in other documents.

This is perhaps a bit confusing. I hesitate to add a bit more text "1st 
of 2 occurences in this papers, 6 other occurrences", or to move the 
toolbar in the left pane, below the search field.

Also, I wonder if "1st of 2 occurences" is correct english. I anybody 
knows, do not hesitate to tell us here.

**Comment by jflesch** [comment]
> total number of occurences accross all documents

Yeah .. with the text above referring to the current document, that's really confusing.
Also, I think if you want to know where you are in the documents matching your query, you can just look at the document list scroll bar.

By the way, counting the number of occurrences in other documents is technically a problem. Thanks to Whoosh, I can easily know which documents contain some keywords, but I can't know the number of occurrences in each one.

I think it's just simpler if we keep focusing all displayed informations on the current document only (after all, it's in the right part of the window).
I also don't think 2 colors are useful (may be confusing to some ?).

Now, another question : When the user clicks the button "next" and reaches the end of the document, what would be best : 
a) Loop back to the first occurrence of the current document
b) Open the next document and go to the next occurrence ?

**Comment by mjourdan** [comment]
1 color is enough indeed if we can't know the total number of occurrences.

To answer your question, I think going to the next document would be a great feature, but we should find a way to make it not too surprising. A simple progress bar as you suggest would be good for that: when the bar is full, we know the next button will jump to the next paper. Perhaps we should use this text then: "1st of 3 matching papers - 1st of 2 occurrence in this paper"?

**Comment by jflesch** [comment]
> "1st of 3 matching papers - 1st of 2 occurrence in this paper"

Too much text IMHO.

However, maybe, on top of the document list, we could display the very same progress bar with a similar text ? I think it would be clearer ?

**Comment by mjourdan** [comment]
Putting text end progress bar would make it related to the paper list instead of the paper currently displayed... Please find a [second mockup](https://github.com/mjourdan/gnome-design/blob/master/paperwork/experiments/find-2.png).

**Comment by jflesch** [comment]
This mockup looks good. I assume the "32" on blue background is the total number of documents in the list ?

**Comment by mjourdan** [comment]
You're right. I made a [third mockup](https://github.com/mjourdan/gnome-design/blob/master/paperwork/experiments/find-3.png), closer to what you discribed in your previous comment.

**Comment by jflesch** [comment]
Actually, I'm confused by this third mockup ... :/

The "2 of 2" refers to the content of the current document, or to the total number of occurrences ?

Either it refers to the content of the current document, in which case it shouldn't be in the document list ; it should on the right, above the pages ;
Or it refers to the total number of occurrences, in which case there are too many documents displayed in your document list ?

**Comment by mjourdan** [comment]
Yes, that's confusing! That's what I thought (so I made mockup number 2), but I wanted to give a try to your suggestion ("on top of the document list, we could display the very same progress bar with a similar text ?"), so we could compare. Now we know.

**Comment by jflesch** [comment]
Yeah, it was a bad idea from me.
Sorry the extra time you had to take to mock it up :/

**Comment by jflesch** [comment]
Hm, I wonder, maybe we can build something starting from your second mockup. What about:

```[<<]  [<] 2 of 3 occurences [>] [>>]```
on top of the pages ?

With the following tooltips when hovering the buttons:

* [>] next occurrence
* [>>] next document
* [<] previous occurrence
* [<<] previous document

--> In other words, let's scrap the total number of documents or total number of occurrences for now ? We can add it back later if we feel a real need for it (and anyway, as I said, it won't be easy to implement).

If we go this way, one question remains : What is the expected behavior of the button [<] when we are on the very first occurrence of the document, or [>] when we are on the last one ? Do we loop back, or do we disable the button ? (same goes for [<<] and [>>] actually)
I guess the most common behavior when searching is looping back ?

What do you think ?

**Comment by mjourdan** [comment]
I was interested in keeping [<][>] close to each other so that user doesn't have to travel much to switch.

We might consider also the following buttons:
- [|<] first occurrence
- [>|] last occurence

Which could do something like:
[<<] white space [|<] [<] 2 of 3 [>] [>|] white space [>>]

When we are on the first occurence of the second document, [|<] and [<] would be disabled. Pressing [<<] would lead to the previous paper, which is also the first, so [<<] would be disabled too. That makes maybe a lot of buttons but avoiding loops makes things more simple I think.

**Comment by jflesch** [comment]
Keeping the buttons together : ok

Regarding first/last occurrence, it means having 6 buttons. I think it's too much.
When you look at Firefox or Gedit, there are no such buttons.
First occurrence could be found by going back to the first page, clicking on one of the first words and clicking "next" (like Firefox). Same goes for last occurrence (last page + click on one of the last words).

**Comment by jflesch** [comment]
Mockup 2 + "[<<] white space [|<] [<] 2 of 3 [>] [>|] white space [>>]" is ok for me.

**Comment by jflesch** [comment]
Displaying the count of documents matching the query: e4c15359c936ca7cc7f9a62b4dee179bc5644fb8

**Comment by jflesch** [comment]
Search bar: a707b583b05cd607b26fb5a523ca0f2a6dcc5a32
I still have to make the button work

**Comment by jflesch** [comment]
Search bar buttons: 652a1de0fac3d0246c3eb1c853517c843cd8fa8e
Still need to highlight the boxes correctly

**Comment by jflesch** [comment]
Searchbar: Highlight / select the target box : fc1262fb77af3597bd8cc22200e38ad9de355112

**Comment by jflesch** [comment]
Immediate loading of boxes when the document is opened: 6bd0babcd068d6921ce6e4ca6e130dd960d486de

**Comment by jflesch** [comment]
Keyboard shortcuts: F3 (next occurrence) / Ctrl+F3 (previous occurrence): 833aecbfa1823fc4a8109a2627f7e6e13191d5bb

**Comment by jflesch** [comment]
All done ! :)

**Comment by tYYGH** [comment]
Great!
Is there a reason why Ctrl+F3 was chosen for the previous occurrence, whereas Shift is usually used to reverse the search?

**Comment by jflesch** [comment]
Because I thought it was Ctrl+F3 the usual one ... I'm going to fix it :-)

**Comment by jflesch** [comment]
Shift+F3: 43224aaefe11c133f869466aaa93f06da4144bb4
