### ISSUE TITLE
scan button in multipage window not translated

### ISSUE THREAD

**Issue by tiramiseb** [openpaperwork/paperwork#538]
In the "Depuis le bac" window, the "Scan" button is not translated, it shows as "Scan" instead of "Numériser".

**Comment by jflesch** [comment]
That's weird ... in multiscan.glade, the button is clearly marked as "translatable", but it doesn't appear in the french translation file

**Comment by jflesch** [comment]
Ok, it seems the problem was that a context was specified for this translation .. and for some reason it messed up the translation.

**Comment by jflesch** [comment]
31fae4419b0a888393d56922442ddf2178033e21
