### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by mjourdan** [openpaperwork/paperwork#559]
One more request to provide a nice way to install Paperwork.

[Flatpak](http://flatpak.org/) is a framework which aims to replace the various packaging systems to deliver desktop applications across different distributions. Flatpak support for Paperwork has been [requested on linuxfr](https://linuxfr.org/nodes/110477/comments/1684266), and is (as an example) [supported  by Lollypop](https://github.com/gnumdk/lollypop/issues/683) (python + gtk3 + lovely gui). I Thought it could be a nice replacement for #466...

**Comment by jflesch** [comment]
I already had a look a while ago. Seems interesting, but I have a feeling it won't be easy :/

**Comment by mjourdan** [comment]
I am [trying to build a flatpak](https://github.com/mjourdan/paperwork/tree/wip-flatpak/flatpak)  but it fails with the following message:

```
========================================================================
Building module paperwork in /home/thamieu/Projets/paperwork-virtualenv/paperwork/flatpak/.flatpak-builder/build/paperwork-1
========================================================================
Error: module paperwork: Can't find makefile
Makefile:25 : la recette pour la cible « org.gnome.Paperwork » a échouée
make: *** [org.gnome.Paperwork] Erreur 1
```

I suppose it is a paperwork issue since all the python dependencies built successfully.

If you want to give a try, here is how to reproduce:

```
git clone https://github.com/mjourdan/paperwork.git
cd paperwork
git checkout wip-flatpak
cd flatpak
make
```

Do you think I should rather open a ticket to the flatpak bug tracker?

**Comment by jflesch** [comment]
I need my Ubuntu Gnome to test with a version of Flatpak recent enough (--> I only have Ubuntu Gnome at home), so I won't be able to test before sometimes (I'm going to lack free time for some times ....).

In the meantime, I suggest you update to the latest 'testing' branch. I've made changes regarding the use of pkg_resources (locales weren't loaded properly for instance). I don't know if it may help you, but it should be included.

**Comment by mjourdan** [comment]
As I am [experiencing some trouble with flatpak](https://github.com/flatpak/flatpak/issues/850), it's unsure when I will be able to get back to this task :/

Though I have updated my [flatpak branch](https://github.com/mjourdan/paperwork/tree/wip-flatpak/flatpak) with the progress I made so far.

**Comment by mjourdan** [comment]
Some progress: I could build and install a flatpak, but could not get it running far:

```
$ flatpak run org.gnome.Paperwork                                                                                                                            
INFO   paperwork.paperwork            Using locales in '/home/thamieu/.var/app/org.gnome.Paperwork/cache/Python-Eggs/paperwork-1.3-py3.4.egg-tmp/paperwork/frontend/share/locale'
INFO   paperwork.paperwork            Initializing pyinsane ...
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_3nzgxgg7/pipe_c2s | /tmp/pyinsane_3nzgxgg7/pipe_s2c
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/lib/python3.4/site-packages/pyinsane2-2.0.9-py3.4.egg/pyinsane2/sane/daemon.py", line 159, in <module>
  File "/app/lib/python3.4/site-packages/pyinsane2-2.0.9-py3.4.egg/pyinsane2/sane/daemon.py", line 115, in main_loop
  File "/app/lib/python3.4/site-packages/pyinsane2-2.0.9-py3.4.egg/pyinsane2/sane/abstract.py", line 45, in init
  File "/app/lib/python3.4/site-packages/pyinsane2-2.0.9-py3.4.egg/pyinsane2/sane/rawapi.py", line 525, in sane_init
AssertionError
```

@jflesch, if you wanna handle this from now, I won't complain

**Comment by jflesch** [comment]
This assert is raised if libsane hasn't been found but sane_init() has been called anyway.
I think you're simply missing libsane.

Anyway, I'm going to have a look. Because we can embed libsane + all the drivers, but we will hardly be able to embed tesseract and all the language data files in a single flatpak.

Problem is, I lack free time currently ... I'm moving next month, so I may not have a lot of free time until then :/

**Comment by jflesch** [comment]
Wow, you did quite an impressive job already it seems. Did you write the .json yourself or is it generated ?

**Comment by mjourdan** [comment]
It's all handwritten, sha256sum copy/pasted package after package ><

**Comment by jflesch** [comment]
Yeah, having a SHA on the branch unstable may be a problem to maintain ;-)

**Comment by jflesch** [comment]
Ok, I've finally taken some time to try to build it on my side.
I've created a branch 'wip-flatpak', based on the branch 'stable', but including your changes.
I've been able to reach the point where you were blocked. Including sane and opensource scanners drivers shouldn't be much of a problem. However, I will soon have 2 problems:
* how to make this flatpak work with proprietary scanner drivers ? (for instance, my annoying Brother scanner)
* how to include Tesseract support for as many languages as possible without making a 600MB flatpak bundle ?

**Comment by jflesch** [comment]
Note to myself, the .json of Flatpak can refer to Git repositories:

```json
    "modules": [
        {
            "name": "gnome-dictionary",
            "sources": [
                {
                    "type": "git",
                    "url": "git://git.gnome.org/gnome-dictionary"
                }
            ]
        }
    ]
```

**Comment by mjourdan** [comment]
> how to make this flatpak work with proprietary scanner drivers ? (for instance, my annoying Brother scanner)

Well, perhaps you should get in touch with flatpak developpers, as [they say](https://github.com/flatpak/flatpak/wiki/Sandbox): 

> We need to figure out how to best get scanner support into the sandbox.

> how to include Tesseract support for as many languages as possible without making a 600MB flatpak bundle ?

Actually I don't even know how to split the actual app from a bundle :/

> Note to myself, the .json of Flatpak can refer to Git repositories:

Ooops, seems I forgot to push some changes. Now there is a couple of git repositories listed in my wip-flatpak branch...

**Comment by jflesch** [comment]
@mjourdan : afaik, python-sane isn't useful

> Now there is a couple of git repositories listed in my wip-flatpak branch...

Do you want me to rename the branch ?

**Comment by jflesch** [comment]
@mjourdan: I think the dependency you were looking for is sane_backend: https://alioth.debian.org/frs/?group_id=30186

**Comment by mjourdan** [comment]
> Do you want me to rename the branch ?

Nope!

 > @mjourdan: I think the dependency you were looking for is sane_backend: https://alioth.debian.org/frs/?group_id=30186

Yeah, probably. I was desperately looking throughout pypi.python.org :(

**Comment by jflesch** [comment]
https://github.com/openpaperwork/paperwork/commit/332e0c30ef75f9f8a558793d7799f81b07b8b285
^ sane-backend added. It now works \o/
For some reason, alioth.debian.org (the official source for sane-backends) makes my flatpak-builder segfaults, so I had to use a mirror.

**Comment by jflesch** [comment]
I've created a nightly build: https://github.com/openpaperwork/paperwork/blob/unstable/flatpak/README.markdown

Remaining to do:
- [ ] check that Flatpak updates work as expected
- [ ] desktop icon
- [ ] Tesseract data files
- [ ] Enable Saned support

**Comment by jflesch** [comment]
[And done !](https://github.com/openpaperwork/paperwork/tree/unstable/flatpak#readme)

**Comment by jflesch** [comment]
I'm going to see if I can submit Paperwork to Flathub.

**Comment by jflesch** [comment]
Flatpak support is complete. But I still need to add Appstream data to publish Paperwork on Flathub ( #691 and #690 )

**Comment by jflesch** [comment]
In case someone comes here from Flathub or Google, looking how to enable scanner support in Paperwork when using Flatpak: [the documentation is here](https://github.com/openpaperwork/paperwork/tree/master/flatpak#readme)
