### ISSUE TITLE
Changing label on many documents

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#580]
(from the helpdesk, ticket=15)

It could be handy to be able to change the labels on many documents at once.

**Comment by cypriani** [comment]
This is a duplicate of #728 (which also covers deleting documents).

**Comment by jflesch** [comment]
Actually, if you look at the dates, it's #728 that duplicated this ticket. Anyway, #728 is broader and probably more appropriate so I'm closing this ticket.
