### ISSUE TITLE
Export : add a dialog to indicate the end of the export

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#585]
https://www.youtube.com/watch?v=UQXoLEdoeiw

**Comment by teto** [comment]
or a notification via libnotify :)

**Comment by jflesch** [comment]
Hm, I'm not very fond of notifications.
I'll have to think of it.

**Comment by tYYGH** [comment]
+1 @jflesch 
Notifications’ purpose is to let the user know of unexpected or unpredictable events, or just the end of a long process (video rendering, printing, etc.)
Exporting is none of the above; a notification would just be annoying.
IMHO, even a pop-up would be annoying. I’d rather see a progress bar that gets replaced by a “Done!” message. As far as I’m concerned, Firefox’ download arrow–icon has just the balance of information and discretion.

**Comment by jflesch** [comment]
Good point

**Comment by jflesch** [comment]
Note to myself: https://wiki.archlinux.org/index.php/Desktop_notifications

**Comment by jflesch** [comment]
I guess it could also be used for the import popup. Notifications allows for buttons so it wouldn't block #567 .

**Comment by jflesch** [comment]
Export: 0ec0f408a1f72e5bc4a14d7cae7cc2c03f5ce31f

**Comment by jflesch** [comment]
Import: e4fe0adc5490c5189184912c87c7f2b88b94b676
