### ISSUE TITLE
[pw-shell 1.1.2] maybe make the shell more REST-like

### ISSUE THREAD

**Issue by tYYGH** [openpaperwork/paperwork#593]
```
19:08:48 [yves:~] 1 $ paperwork-shell import ~/Desktop/13-02-2017-Ordre\ de\ Service.pdf 
/ici/home/yves/Desktop/13-02-2017-Ordre de Service.pdf:
{'Document(s)': 1, 'Image file(s)': 0, 'PDF': 1, 'Page(s)': 4}
```
Now I want to check the labels, maybe add some more. Were “I” a program instead of a human, I may want to also retrieve the thumbnails, and so on. I can’t do any of this because the above information shows no ID. You may want to model the shell’s I/O after the REST API way of doing stateless requests/answers.

**Comment by jflesch** [comment]
I think I see two tickets here:
- make the shell more REST-like (>= paperwork 2.0)
- ```paperwork-shell import``` should return the ID of the new document / new pages (OK for paperwork 1.2)

**Comment by jflesch** [comment]
(I'm a little bit tired and misunderstood your ticket at first, sorry)

**Comment by tYYGH** [comment]
No problem ;-) I sympathize.

**Comment by jflesch** [comment]
That should do the trick :
35e45fd5eb0897b123ac23c29f43b7923c99afde
b2ed6054cc38af0bf4c4593d9d4bd398b3559ed0

Option ```-v``` (verbose) has been replaced by ```-q``` (quiet) --> paperwork-shell is verbose by default.
With ```paperwork-shell -bq``` (batch + quiet), the output is guaranteed to be only JSON (except for the command 'dump').

Example:
```json
$ paperwork-shell -bq import file:///home/jflesch/tmp/pouet.pdf
{
    "guessed_labels": [
        {
            "docid": "20170602_1513_12",
            "labels": [
                "Documentation"
            ]
        }
    ],
    "imports": {
        "imported_file_uris": [
            "file:///home/jflesch/tmp/pouet.pdf"
        ],
        "new_docs": [
            {
                "docid": "20170602_1513_12",
                "labels": []
            }
        ],
        "new_docs_pages": [
            "20170602_1513_12|0",
            "20170602_1513_12|1"
        ],
        "stats": {
            "Document(s)": 1,
            "Image file(s)": 0,
            "PDF": 1,
            "Page(s)": 2
        },
        "upd_docs": [],
        "upd_docs_pages": []
    },
    "status": "ok"
}
```

**Comment by tYYGH** [comment]
Well done! Thanks 👍
