### ISSUE TITLE
paperwork-shell import doesn't run OCR on scanned PDF.

### ISSUE THREAD

**Issue by jstenback** [openpaperwork/paperwork#600]
Seems as if paperwork-shell import somefile.pdf does indeed index the content of the pdf if the pdf actually contains text that it can extract, and then guesses labels etc. But this is not happening with a scanned pdf, i.e. a pdf with a bitmap in it.

**Comment by jstenback** [comment]
For the record, I'm seeing this with 1.1.2.

**Comment by jflesch** [comment]
https://github.com/openpaperwork/paperwork-backend/commit/8848e0c6083f2b33f0ce7f865dee413a782030c9
