### ISSUE TITLE
Paperwork eats 100% CPU

### ISSUE THREAD

**Issue by fabrice-regnier** [openpaperwork/paperwork#601]
Hi,

I open paperwork.
I mouve the mouse over the Edit button or the Delete button, on the right, of a scanned doc.
Then paperwork eats 100% cpu until i quit.

If i execute paperwork without doing anything, the cpu will keep calm.

lsof didn't show anything special nor the paperwork logs. However, strace shows me a lot of 

```
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 0) = 0 (Timeout)

```

Just tell me if you want me to do somehting.

```
FR-PORT:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.0 (stretch)
Release:        9.0
Codename:       stretch

FR-PORT:~# uname -a
Linux FR-PORT 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux
```

regards,

f.

**Comment by jflesch** [comment]
Reproduced

**Comment by jflesch** [comment]
Reproduced on GNU/Linux Ubuntu Gnome (~= debian testing), but not on GNU/Linux Debian stable.
I have a feeling it could be a GTK+ bug.

**Comment by jflesch** [comment]
Not reproduced anymore with Ubuntu Gnome 17.04 and the latest changes in the unstable branch
