### ISSUE TITLE
Document list disappear when deleting a document

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#607]
2 people have reported that their document list disappear when deleting a document

**Comment by teto** [comment]
in my case (using master) it also disappears when scanning something. Eventually it reappears but after 5sec.

**Comment by MaryFr** [comment]
Sometimes bugs out completely and can't delete a second document - for example here when I deleted the 47th image, couldn't delete the last (48th)
[Diagnostic 2017-04-02.txt](https://github.com/jflesch/paperwork/files/888316/Diagnostic.2017-04-02.txt)
. Partial diagnostic below and full attached:
INFO   paperwork_backend.docsearch    Indexing new doc: 20170401_2202_08
ERROR  paperwork.frontend.util.jobs   ===> Job IndexUpdater:0 raised an exception: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'F:\\Scans\\Paperwork\\20170401_2202_08\\paper.47.jpg'
ERROR  paperwork.frontend.util.jobs    0: site-packages\paperwork-1.1.2-py3.4.egg\paperwork\frontend\util\jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: site-packages\paperwork-1.1.2-py3.4.egg\paperwork\frontend\mainwindow\__init__.py: L  423: do
ERROR  paperwork.frontend.util.jobs    2: site-packages\paperwork_backend-1.1.2-py3.4.egg\paperwork_backend\docsearch.py: L  284: add_doc
ERROR  paperwork.frontend.util.jobs    3: site-packages\paperwork_backend-1.1.2-py3.4.egg\paperwork_backend\docsearch.py: L  245: _update_doc_in_index
ERROR  paperwork.frontend.util.jobs    4: site-packages\paperwork_backend-1.1.2-py3.4.egg\paperwork_backend\img\doc.py: L  403: get_docfilehash
ERROR  paperwork.frontend.util.jobs    5: site-packages\paperwork_backend-1.1.2-py3.4.egg\paperwork_backend\img\page.py: L  295: get_docfilehash
ERROR  paperwork.frontend.util.jobs    6: site-packages\paperwork_backend-1.1.2-py3.4.egg\paperwork_backend\common\doc.py: L  414: hash_file
ERROR  paperwork.frontend.util.jobs   ---> Job IndexUpdater:0 was started by:
ERROR  paperwork.frontend.util.jobs    0:            paperwork: L    6: <module>
ERROR  paperwork.frontend.util.jobs    1: site-packages\paperwork-1.1.2-py3.4.egg\paperwork\paperwork.py: L  151: main
ERROR  paperwork.frontend.util.jobs    2: site-packages\paperwork-1.1.2-py3.4.egg\paperwork\frontend\mainwindow\__init__.py: L 2273: __on_doc_exam_end
ERROR  paperwork.frontend.util.jobs    3: site-packages\paperwork-1.1.2-py3.4.egg\paperwork\frontend\util\jobs.py: L  256: schedule
INFO   paperwork.frontend.util.actions Action: [Opening diagnostic dialog]
INFO   paperwork.frontend.util        UI file used: C:\Program Files (x86)\Paperwork\data\diag\diagdialog.glade
INFO   paperwork.frontend.diag        ====== START OF SYSTEM INFO ======
INFO   paperwork.frontend.diag        os.name: nt
INFO   paperwork.frontend.diag        sys.version: 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
INFO   paperwork.frontend.diag        platform.architecture: ('64bit', 'WindowsPE')
INFO   paperwork.frontend.diag        platform.platform: Windows-10-10.0.14393-SP0
INFO   paperwork.frontend.diag        platform.processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
INFO   paperwork.frontend.diag        platform.version: 10.0.14393
INFO   paperwork.frontend.diag        platform.linux_distribution: ('', '', '')
INFO   paperwork.frontend.diag        platform.win32_ver: ('10', '10.0.14393', 'SP0', 'Multiprocessor Free')
INFO   paperwork.frontend.diag        multiprocessing.cpu_count: 8
ERROR  paperwork.frontend.diag        'module' object has no attribute 'sysconf'
Traceback (most recent call last):
  File "site-packages\paperwork-1.1.2-py3.4.egg\paperwork\frontend\diag\__init__.py", line 78, in _get_sysinfo
AttributeError: 'module' object has no attribute 'sysconf'
INFO   paperwork.frontend.diag        ====== END OF SYSTEM INFO ======

**Comment by jflesch** [comment]
Unfortunately, the diagnostic you reported was of when you restarted Paperwork.
Diagnostic would have been more helpful if obtained right after the problem occurred (without restarting Paperwork).

However:
1) I can have a look for 1.2 to make sure that Paperwork keeps loading in this case.
2) In the meantime, you can work around this problem by deleting F:\Scans\Paperwork\20170401_2202_08\papers.47.* manually while Paperwork is not running.

**Comment by MaryFr** [comment]
OK - thanks, will remember to run diagnostic after it happens :-) as it's happened a few times now

**Comment by jflesch** [comment]
@teto & to the other people having this problem : When it happens, does resizing the main window make the document list reappear ?

**Comment by tYYGH** [comment]
@jflesch I have a redraw problem that could be related, eg. after I change the labels of a document, after I scan a new page, after a search is finished…
Always, I get the document list back by switching the focus to another window and back to Paperwork (which is a simple mouse movement for me as I use focus-follows-mouse).
Iconifying then restoring the window does not work; I guess Gnome keeps the window state in cache in this case and does not actually send redraw events…

**Comment by jstenback** [comment]
When I see this issue resizing the main window does indeed make the document list reappear.

**Comment by jflesch** [comment]
Yeah, unfortunately, if true for everybody else who have this ticket ... it sounds more like a GTK+ issue than a Paperwork issue ... and it will be painful to track down :/

**Comment by eliotb** [comment]
I can confirm that I have sometimes seen the same as @tYYGH. It seems that it can happen any time the document list should be refreshed, e.g. when filtering, or when returning from the edit Properties view, or after scanning a new document.

It is, unfortunately, not completely repeatable.

**Comment by jflesch** [comment]
Same workaround than #629:
Remove / re-add the GTK widgets (GtkRevealer) as required : 1ab7540
