### ISSUE TITLE
Scanner greyed out, Paperwork Unresponsive

### ISSUE THREAD

**Issue by MaryFr** [openpaperwork/paperwork#617]
Paperwork has stopped recognising the scanner (Epson XP-960) after it went to sleep. I've tried the following:
- opening the lid to wake it up
- turning printer on and off
- closing the application (had to force close as unresponsive)
- rebooting PC
- unplugging USB and re-plugging
- removing and re-installing the printer
- re-installing Paperwork

I can scan from other programs such as Windows Fax & Scan and EPSON Scan and can print to the printer from other applications.

Love the application, but no idea how to diagnose / fix this error!

![20170329_paperwork issue](https://cloud.githubusercontent.com/assets/26764522/24450328/6b3367e4-1472-11e7-8344-6c5b707321b9.JPG)
![20170329_paperwork issue2](https://cloud.githubusercontent.com/assets/26764522/24450478/f96ea578-1472-11e7-8211-7a5888cb9938.JPG)

**Comment by MaryFr** [comment]
Closing. Following a restart (and choosing the scanner from the list) it's now working again. 

May need to work out why it has a problem with the scanner going to sleep/waking up?

**Comment by jflesch** [comment]
Currently, diagnostic on Windows with the release version when the application entirely crashes or freezes is pretty much impossible.

I would need the diagnostic output, but currently you can only get it from the [diagnostic dialog](https://openpaper.work/fr/helpdesk/kb/1/), but obviously you can only get it if Paperwork is still running. Even then, when it comes to scanners on Windows, the diagnostic output is usually insufficient.

There are 2 other options:
- I can make Paperwork write a log file. I will consider it for the next release of Paperwork.
- I could buy the same scanner than you. Unfortunately, I'm currently low on funds.

**Comment by MaryFr** [comment]
If it happens again I'll try that.
Sadly, as for funds, that makes two of us, otherwise would sub you :-)
