### ISSUE TITLE
Labels reselected when new label is created.

### ISSUE THREAD

**Issue by eliotb** [openpaperwork/paperwork#624]
When a document is first scanned or imported, some labels are applied automatically (so far for me they are always wrong!).

To correct this, enter the Properties for the document, deselect the wrong labels, then create a new label.
Once the new label is created, it is selected - good.

BUT also the previously deselected labels are selected again.  I think this shouldn't happen.
(paperwork v 1.1.1)

**Comment by jflesch** [comment]
Duplicate of #518
