### ISSUE TITLE
https://openpaper.work/ is down

### ISSUE THREAD

**Issue by razor20171** [openpaperwork/paperwork#637]
https://openpaper.work/ is down... Where can I download package for windows ?

**Comment by jflesch** [comment]
https://github.com/openpaperwork/paperwork/releases/tag/1.1.2
https://github.com/openpaperwork/paperwork/releases/download/1.1.2/paperwork_1.1.2a_win64_installer.exe

I know. I'm hosting openpaper.work on my personal ADSL connection. And right now, my line is down ...

**Comment by jflesch** [comment]
Back online
