### ISSUE TITLE
ui: merge "save as" and "export" button

### ISSUE THREAD

**Issue by teto** [openpaperwork/paperwork#638]
I often use the "export" feature but I find the workflow too slow.
First you have to choose a destination to save to (could default to ~/Documents or last saved path).
At the beginning I would often close the window immediately thinking that choosing the output folder would automatically export the document (but no, you have to hit that "Export" button).

**Comment by jflesch** [comment]
Duplicate of #586

**Comment by teto** [comment]
sorry, I tried to upgrade to unstable before asking but I pulled the wrong branch xD
