### ISSUE TITLE
paperwork-shell install: Unknown command install

### ISSUE THREAD

**Issue by nodiscc** [openpaperwork/paperwork#642]
After following installation instructions from https://github.com/openpaperwork/paperwork/blob/unstable/doc/install.debian.markdown, the command `paperwork-shell install` fails with `Unknown command install` and prints out the paperwork-shell help text `Possible commands are...`.

Everything seems to work fine except this minor glitch (apparently only used to create a .desktop launcher)

**Comment by jflesch** [comment]
Those instructions will be valid for 1.2.x (currently in branch 'testing').
The last released version is the 1.1.2 ('stable'). [Instructions for 1.1.2 does not include 'paperwork-shell install'](https://github.com/openpaperwork/paperwork/blob/stable/doc/install.debian.markdown).

**Comment by jflesch** [comment]
Doc has been slightly clarified: https://github.com/openpaperwork/paperwork/blob/stable/doc/install.debian.markdown
