### ISSUE TITLE
Can't import JPG files

### ISSUE THREAD

**Issue by nodiscc** [openpaperwork/paperwork#643]
Sorry if this is a duplicate, I could not find another issue related to this. I have a lot of previously scanned documents in JPEG format that I would like to import. I have followed install instructions from https://github.com/openpaperwork/paperwork/blob/unstable/doc/install.debian.markdown. PDF import works fine. https://github.com/openpaperwork/paperwork/blob/unstable/doc/usage.pdf seems to suggest that JPG image imports are supported.

However when I import a directory containing multiple JPG/PDF files, only PDF files are imported. Selecting a single `.jpg` file for import shows an error dialog:

`Import failed: 'PdfDoc' obejct has no attribute 'add_page'`

Maybe JPG import is not supported in the current pip release?

**Comment by jflesch** [comment]
JPEG supports is in Python3-piilow (or python3-pil). Whatever Python3-pillow supports, Paperwork does support it.

But this is not what the error message describes here.

Can you check that the versions of paperwork-backend and paperwork on your system are the same please ?
Can you also check there are no other versions installed ?

**Comment by jflesch** [comment]
Nevermind ! I see the problem. You tried to import an image file while having a PDF file opened.
Paperwork never modifies PDF files, so this operation is not allowed. It shouldn't have let you do that.

**Comment by jflesch** [comment]
Fixed for 1.2: 51fcf6897d18026ada8e315fc1849320d8daf94a

**Comment by nodiscc** [comment]
Thanks; as you said importing a JPG to a blank document worked perfectly.

However it will take me a very long time to import all my jpg scans one by one (~500 files) - I will open a new issue for multiple JPG files import :)

**Comment by jflesch** [comment]
Already done in 1.2:
#420
#94
:)

**Comment by nodiscc** [comment]
@jflesch Sorry for the noise :) Pretty damn impressive software. I'll wait for 1.2 to be released. I think you could already push the PDF/lyx docs to the website (it was not obvious where to find them, had to use Github code search).

What is the upgrade path to 1.2? Do I have to run the process from https://github.com/openpaperwork/paperwork/blob/unstable/doc/install.debian.markdown again?

**Comment by jflesch** [comment]
Well the PDF won't really be pushed on the website at any point. They will be integrated manuals in Paperwork itself (hence why they actually are PDFs instead of HTML pages).

Regarding the installation process, yes pretty much. I would also advise [uninstalling](https://github.com/openpaperwork/paperwork#uninstall) first before reinstalling the new version.
