### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by bracco23** [openpaperwork/paperwork#645]
Hello!

I'm really interested in this project, I was thinking of developing something similar but why reinvent the wheel? anyway, interested in the Windows installer, I was trying to get into the site but it is not responding, not even to the ping. Anything wrong?

**Comment by jflesch** [comment]
Yep. The website is hosted on my ADSL line, and I guess it went down once again... (I'm going to check in a few hours actually).
In the meantime, you still can get the Windows version here : https://github.com/openpaperwork/paperwork/releases/tag/1.1.2

**Comment by jflesch** [comment]
back online
