### ISSUE TITLE
https://openpaper.work Down?

### ISSUE THREAD

**Issue by jonathanweinberg** [openpaperwork/paperwork#652]
Seems that https://openpaper.work is down at the moment. I got, and confirmed with a few people outside my local area / networks that you only get:

```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.25 (Debian) Server at openpaper.work Port 443
```

**Comment by jflesch** [comment]
Yep, sorry for that. I host it on my personal ADSL connection to spare money .. and let's just say it's crappy ...

**Comment by jonathanweinberg** [comment]
Where can I email you?

**Comment by jflesch** [comment]
jflesch@kwain.net
