### ISSUE TITLE
Archlinux packaging issues with paperwork 1.2

### ISSUE THREAD

**Issue by StreakyCobra** [openpaperwork/paperwork#659]
Hi,

I updated the Archlinux package to version 1.2, and two problems were [reported](https://aur.archlinux.org/packages/paperwork/):

- The desktop entry is not longer provided
- Localization seems to be broken

-----

### The desktop entry is not longer provided

I read that we should now call `paperwork-shell install`,  but this is causing problem with the way Archlinux's packaging system works.

The way Archlinux build the package is the following:

1. It download the sources
2. It extract them into a `src/` folder, like `/home/fabien/paperwork/src/`
3. It build the software **as a normal user** in a `pkg/<pkgname>` prefix, like `/home/fabien/paperwork/pkg/paperwork/`, which then contains for instance:

        [...]
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/__init__.py
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/config.py
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/deps.py
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/docexport.py
        [...]
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/img/__pycache__/__init__.cpython-36.opt-1.pyc
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/img/__pycache__/doc.cpython-36.opt-1.pyc
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/img/__pycache__/page.cpython-36.opt-1.pyc
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/pdf
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork_backend/pdf/__init__.py
        [...]
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork/frontend/import/__init__.py
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork/frontend/import/importaction.glade
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork/frontend/import/importfileselector.glade
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork/frontend/import/__pycache__
        [...]
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/bin/paperwork-shell
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/bin/paperwork
        [...]
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/icons/hicolor/128/apps/paperwork.png
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/icons/hicolor/150/apps/paperwork.png
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/icons/hicolor/16/apps/paperwork.png
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/icons/hicolor/160/apps/paperwork.png
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/icons/hicolor/192/apps/paperwork.png
        [...]
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/locale/de/LC_MESSAGES/paperwork.mo
        /home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/paperwork/frontend/share/locale/fr/LC_MESSAGES/paperwork.mo
        [...]

4. Then it creates a package (kind of a zip file) that contains these files with truncated path:

        [...]
        /usr/lib/python3.6/site-packages/paperwork_backend/__init__.py
        /usr/lib/python3.6/site-packages/paperwork_backend/config.py
        /usr/lib/python3.6/site-packages/paperwork_backend/deps.py
        /usr/lib/python3.6/site-packages/paperwork_backend/docexport.py
        [...]
        /usr/lib/python3.6/site-packages/paperwork_backend/img/__pycache__/__init__.cpython-36.opt-1.pyc
        /usr/lib/python3.6/site-packages/paperwork_backend/img/__pycache__/doc.cpython-36.opt-1.pyc
        /usr/lib/python3.6/site-packages/paperwork_backend/img/__pycache__/page.cpython-36.opt-1.pyc
        /usr/lib/python3.6/site-packages/paperwork_backend/pdf
        /usr/lib/python3.6/site-packages/paperwork_backend/pdf/__init__.py
        [...]
        /usr/lib/python3.6/site-packages/paperwork/frontend/import/__init__.py
        /usr/lib/python3.6/site-packages/paperwork/frontend/import/importaction.glade
        /usr/lib/python3.6/site-packages/paperwork/frontend/import/importfileselector.glade
        /usr/lib/python3.6/site-packages/paperwork/frontend/import/__pycache__
        [...]
        /usr/bin/paperwork-shell
        /usr/bin/paperwork
        [...]
        /usr/paperwork/frontend/share/icons/hicolor/128/apps/paperwork.png
        /usr/paperwork/frontend/share/icons/hicolor/150/apps/paperwork.png
        /usr/paperwork/frontend/share/icons/hicolor/16/apps/paperwork.png
        /usr/paperwork/frontend/share/icons/hicolor/160/apps/paperwork.png
        /usr/paperwork/frontend/share/icons/hicolor/192/apps/paperwork.png
        [...]
        /usr/paperwork/frontend/share/locale/de/LC_MESSAGES/paperwork.mo
        /usr/paperwork/frontend/share/locale/fr/LC_MESSAGES/paperwork.mo
        [...]

5. The built package can then be installed by the archlinux package manager, which will roughly unzip the file at root. 

So if I try to call `paperwork-shell install` when the package is being built, it will try to install the file in `/usr/lib/python3.6/site-packages/paperwork/` directly at build time, and we want it to actually be in `/home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/lib/python3.6/site-packages/paperwork/` so that it get included in the package.

**Q:** In short, is there a way to customize the prefix where `paperwork-shell install` places the files?

-----

### Localization seems to be broken

I haven't seen anything special in this release about localization, did I miss something? Maybe translations are also installed by `paperwork-shell install`?

**Comment by jflesch** [comment]
> Localization seems to be broken

Weird. There is one change related to that : localisation files are now stored alongside python files using pkg_resources. (see setup.py and src/paperwork/frontend/util/__init__.py : get_resource_path())

**Comment by StreakyCobra** [comment]
Listing the files of the built package (`yaourt -Ql paperwork | grep .mo$`):

```
paperwork /usr/paperwork/frontend/share/locale/de/LC_MESSAGES/paperwork.mo
paperwork /usr/paperwork/frontend/share/locale/fr/LC_MESSAGES/paperwork.mo
```

There seems to be placed only in `/usr/paperwork`, and before (`1.1.2`) they were packaged in `/usr/share/locale`:

```
paperwork /usr/share/locale/de/LC_MESSAGES/paperwork.mo
paperwork /usr/share/locale/fr/LC_MESSAGES/paperwork.mo
```

I don't know if I'm supposed to move file there on packaging side?

**Comment by jflesch** [comment]
Nothing should be in /usr/paperwork ... (God setuptools/distutils can be painful to use sometimes ...)

**Comment by jflesch** [comment]
Regarding the desktop shortcut, as part of the building process, isn't it possible to do something similar to the following code ?

```sh
cat > /usr/share/applications/paperwork.desktop << EOF
[Desktop Entry]
Type=Application
Comment=You can grep dead trees
Name=Paperwork
GenericName=Personal Document Manager
Categories=Office;Scanning;
Icon=paperwork
Terminal=false
Version=1.2
Keywords=document;scanner;ocr;
Exec=paperwork
EOF
```

?

**Comment by StreakyCobra** [comment]
Here are the command the PKGBUILD is running if it can help identifying/reproducing the problem:

```bash
build() {
  cd "${srcdir}/${pkgname}-backend-${pkgver}"  # Goes into the backend source folder
  python setup.py build  # Build

  cd "${srcdir}/${pkgname}-${pkgver}" # Goes into the frontend source folder
  python setup.py build  # Build
}

package() {
  cd "${srcdir}/${pkgname}-backend-${pkgver}"  # Goes into the backend source folder
  python setup.py install --prefix=/usr --root="${pkgdir}" --optimize=1  # Install it in the prefix

  cd "${srcdir}/${pkgname}-${pkgver}"  # Goes into the frontend source folder
  python setup.py install --prefix=/usr --root="${pkgdir}" --optimize=1   # Install it in the prefix

  install -D -m644 COPYING "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"  # Copy the license
}
```

**Comment by jflesch** [comment]
Regarding the locales, I need to have another look. It's probably some kind of mistake in Paperwork's setup.py.

**Comment by StreakyCobra** [comment]
> Regarding the desktop shortcut, as part of the building process, isn't it possible to do something similar to the following code ?

If I undertand your question correctly, no, because during the building process the file should be:

```
/home/fabien/dev/archlinux/aur/paperwork/pkg/paperwork/usr/share/applications/paperwork.desktop
```

in order to be included in the package.

If it is hardcoded as `/usr/share/applications/paperwork.desktop` then it will try to impact the system directly instead of incorporating the file inside the package.

**Comment by StreakyCobra** [comment]
If I find some time I will try to have a look at the build system to identify where all this come from.

**Comment by jflesch** [comment]
For reference, on a Debian GNU/Linux jessie, the locale files end up in the egg file /usr/local/lib/python3.4/dist-packages/paperwork-1.2.post3-py3.4.egg

**Comment by jflesch** [comment]
And inside this egg file, they have the following paths:
```
paperwork/frontend/locale/fr/LC_MESSAGES/paperwork.mo
paperwork/frontend/locale/uk/LC_MESSAGES/paperwork.mo
paperwork/frontend/locale/de/LC_MESSAGES/paperwork.mo
```

**Comment by jflesch** [comment]
For the .desktop file: the command (and the path indicated) I gave you is just an example. What I'm suggesting here is simply that *you* generate the .desktop file as part of the build process of Paperwork (in the function ```build```).

In the end, when installed, paperwork.desktop must end up being in either ```/usr/share/applications/``` or ```/usr/local/share/applications/``` or ```~/.local/share/applications/``` .

**Comment by StreakyCobra** [comment]
Oh, of course I can generate it myself :-) I just wanted to try finding the issue in order to stay as close as possible to upstream.

**Comment by jflesch** [comment]
Regarding the .desktop, it's not actually an issue. As you saw, it's generated by ```paperwork-shell install```. But this command is intended for manual / not-distribution-packaged installations. I guess I should document that .... :-)

**Comment by StreakyCobra** [comment]
Ok, but did you do anything special before? Because it was present without any intervention on packaging side.

**Comment by jflesch** [comment]
Yep, before it was directly part Paperwork sources and was installed by setup.py. But it made more troubles than it solved (too often it didn't ended up in the expected location ... just like the locales right now ....)

**Comment by StreakyCobra** [comment]
Ok, I got it now :-) I'll add the desktop entry in the packaging side then.

For the locales, I can also probably handle this on packaging side, but I'm not sure there is something more as you said that "Nothing should be in /usr/paperwork", and currently the building put those files there:

    /usr/paperwork/frontend/aboutdialog/paperwork.svg
    /usr/paperwork/frontend/doc/hacking.pdf
    /usr/paperwork/frontend/doc/intro.pdf
    /usr/paperwork/frontend/doc/intro_fr.pdf
    /usr/paperwork/frontend/doc/translating.pdf
    /usr/paperwork/frontend/doc/usage.pdf
    /usr/paperwork/frontend/mainwindow/paperwork_halo.svg
    /usr/paperwork/frontend/share/icons/hicolor/100/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/128/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/150/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/16/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/160/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/192/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/22/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/24/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/256/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/30/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/32/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/36/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/42/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/48/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/50/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/512/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/64/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/72/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/96/apps/paperwork.png
    /usr/paperwork/frontend/share/icons/hicolor/scalable/apps/paperwork.svg
    /usr/paperwork/frontend/share/icons/hicolor/scalable/apps/paperwork_halo.svg
    /usr/paperwork/frontend/share/locale/de/LC_MESSAGES/paperwork.mo
    /usr/paperwork/frontend/share/locale/fr/LC_MESSAGES/paperwork.mo

**Comment by jflesch** [comment]
Something is wrong with setup.py .... this should definitively not happen :/
I'll try to have a look, but unfortunately, I'm moving, so I won't be able to have a look before end of next week :(

**Comment by StreakyCobra** [comment]
Ok, take your time. I'll already fix the desktop entry on my side, and suggest people who have an issue with the language for now to revert to previous version in the meantime.

**Comment by tYYGH** [comment]
Hi! FWIW, I’m the Archlinux user who reported the 2 issues ;-)
Unfortunately, I’ll be away for the next 14 days, but after that, if some things need to be tested, I can help. Cheers,
Y.

**Comment by Lucki** [comment]
For generating desktop files at packaging there's an existing tool named [gendesk](https://github.com/xyproto/gendesk). Keep it up 👍

**Comment by StreakyCobra** [comment]
Thanks for the pointer. FYI I'm having a personal situation these days and I'm also organizing a music camp that will take place next week, so I don't have the state of mind nor the time to dig with this issue right now. If some Arch users are motivated to fix it: PR to https://github.com/StreakyCobra/aur-paperwork and I'll do my best to publish it.

**Comment by klemens** [comment]
The arch package works fine for me if I use the `1.2.post3` instead of the `1.2` tag, which contains some [package-related fixes](https://github.com/openpaperwork/paperwork/compare/1.2...1.2.post3). See https://github.com/StreakyCobra/aur-paperwork/pull/2 for the updated package script.

**Comment by jflesch** [comment]
Hm, does it work with 1.2.post3 ? If so, can I close this issue ?

**Comment by StreakyCobra** [comment]
Everything seems fine with it yes. I haven't received any complaint, so I presume everything is all right now!

Thanks @jflesch, @klemens and @Lucki for the work!

**Comment by jflesch** [comment]
Thank *you* for the AUR packaging :)
