### ISSUE TITLE
ScanSnap fi-5110EOX2 on Windows 7

### ISSUE THREAD

**Issue by chk1** [openpaperwork/paperwork#661]
I have a Fujitsu ScanSnap fi-5110EOX2 scanner which I can't get to work with Paperwork on Windows 7. It is not available in the scanner dropdown menu in the application's settings.

I have an additional Canon CanoScan Lide 100 flatbed scanner connected, that one works fine with Paperwork (it appears twice in the log, device ID \0000 and \0001, not exactly sure why).

This is the relevant part from the diagnosis screen, I believe ([full log here](https://gist.github.com/chk1/58c03f01d94ce67109a2aad9a2b63822)):

```
WARNING pyinsane2.wia.abstract         Failed to access scanner ('{6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\\0002', 'fi-5110EOX2') : WIA: Failed to open {6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\0002
ERROR  pyinsane2.wia.abstract         WIA: Failed to open {6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\0002
Traceback (most recent call last):
  File "site-packages\pyinsane2-2.0.10-py3.4-win-amd64.egg\pyinsane2\wia\abstract.py", line 567, in get_devices
  File "site-packages\pyinsane2-2.0.10-py3.4-win-amd64.egg\pyinsane2\wia\abstract.py", line 413, in __init__
  File "site-packages\pyinsane2-2.0.10-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 79, in open
  File "site-packages\pyinsane2-2.0.10-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 34, in wait
  File "site-packages\pyinsane2-2.0.10-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 39, in do
  File "site-packages\pyinsane2-2.0.10-py3.4-win-amd64.egg\pyinsane2\wia\rawapi.py", line 74, in _open
pyinsane2.wia.rawapi.WIAException: WIA: Failed to open {6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\0002
```

Additional notes:
The Fujitsu scanner does work with Paperwork on Ubuntu 16.04 on my laptop and works with the default Fujitsu scan software on Windows.

For testing I also built and installed pyinsane2 as a Python 3 (3.6.2 32bit) package on Windows, tested with the following script (from the example scripts in the README):
```
devices = pyinsane2.get_devices()
print(devices)
``` 
I get a similar error, [full log here](https://gist.github.com/chk1/581fe0f64a3e79d66023817d99a6ff32) (the Canon scanner was also attached to the computer when I ran this).

**Comment by jflesch** [comment]
Weird. Unfortunately, the only thing I can tell from the logs is that Paperwork was unable to access the scanner (.. which we already know without the logs ...).
Without having the same hardware than you, I don't think I will be able to do much for now.

I'll try to improve pyinsane error messages in the next versions of Paperwork.

**Comment by jflesch** [comment]
[ScanSnap fi-5110EOX2 does not support TWAIN  and ISIS standards](http://origin.pfultd.com/downloads/IMAGE/manual/fi-5110eox2/p3pc-1152-03en.pdf) (p3). [Similar models do not support WIA either. You can make them work with TWAIN with some hacks](http://coopology.com/2014/10/fujitsu-artificial-market-segmentation-or-how-to-make-a-mac-scansnap-fi-5110eoxm-work-in-windows-8-1/). 

So the question is actually: Are you sure your scanner supports WIA (or at least TWAIN) ? Does it work with other third-party applications ?

**Comment by chk1** [comment]
For Windows I haven't found any universal TWAIN or WIA drivers. 

IrfanView and GIMP support scanning from TWAIN devices (most Canon scanners and webcams I had work with this), but it doesn't list the ScanSnap as an available scanner. 

Here's the TWAIN source selection screen:
![image](https://user-images.githubusercontent.com/828496/36862635-b0c20cba-1d87-11e8-9168-438092b61359.png)

There are a few other 3rd party, propietary options like Vuescan. I'm not sure how that software works exactly, I think they implement the propietary Fujitsu protocol in some way.

When opening this issue I wasn't sure how pyinsane/paperwork did its work on Windows, but ultimately seems to be a driver issue, like you linked (thanks for that information though, I will try that!). 
I was confused because it worked on Linux, not only in Paperwork, but in other standard Gnome scan software as well. The Linux drivers for that device might be less restrictive / more compatible.

**Comment by jflesch** [comment]
Yep, I find it quite funny that Fujitsu drivers are obviously better on Linux than on Windows :-D

Anyway, on Windows Pyinsane supports only WIA scanners at the moment, so I'm going to close this ticket. Hopefully later I may have time to add Twain support, but it will mean making the hack work for you.

**Comment by chk1** [comment]
Thanks a lot though, the TWAIN hack worked flawlessly :)

The USB ID of the fi-5110EOX2, for anyone searching: `USB\VID_04C5&PID_1096`
