### ISSUE TITLE
'paperwork-shell help install' fails due to missing docstrings

### ISSUE THREAD

**Issue by torwag** [openpaperwork/paperwork#662]
Hi,
below
https://github.com/openpaperwork/paperwork/blob/24b35502eacae3b6a166ef821345f1f39f22caa0/src/paperwork/frontend/shell.py#L44:L47

The docstring for the function install is missing. This causes the 'paperwork-shell help' function to crash as it receives an object of NoneType instead of a string. Easiest would be to add the string, even better to wrap this in a try-except structure to prevent this little glitch in the future.
Sorry would have submitted a patch, but being on mobile just now, noticed it a few days ago.
If I find time I will add a patch, if not done already

**Comment by torwag** [comment]
if there is a price for the fastest developer reaction... here it should go ;)

**Comment by jflesch** [comment]
:-)

**Comment by torwag** [comment]
Do I see this right, that install "only" adds paperworks to the linux desktop environment. I do not see any methods for Windows. Calling it install seems to me a bit misleading as people might expect the entire program gets moved from a possible local folder into system folders for a system wide installation. Further more, that might be more an task for the package managers of the individual distros.  Honestly speaking, I feel that this function is a bit out of scope for the paperwork-shell function set. 
I know they are used after installation to check for dependencies and add the desktop stuff. 
Would it not be more appropriate to move/call those functions (chk_pkg and install) directly into the setup.py? Or keep them there, but keep them out of the help function, as most users would not need them after installation? Just thinking...

**Comment by jflesch** [comment]
AFAIK, it's not possible to move 'chkdeps' in setup.py. It would mess with setuptools/distutils/etc.
Regarding 'install', it was done in 'setup.py'. Unfortunately, it seems impossible to get it to put files in specific places (sometimes resources are stored in egg files, sometimes ```sys.exec_prefix``` points to unexpected locations, etc).

**Comment by jflesch** [comment]
94e6280128f61db0e4c8f1c5cc866df62eb18edb
