### ISSUE TITLE
Export failed : error while writing to output stream

### ISSUE THREAD

**Issue by AdnanMuhib** [openpaperwork/paperwork#663]
hi, 
I opened an Image in paperwork and after ocr was completed , on export document as pdf option I received the error.
Export failed : error while writing to output stream

is something wrong with the installation or in the release. Looking for the solution . Thanks.

![error](https://user-images.githubusercontent.com/18069154/29293077-10059b90-8163-11e7-960a-7b9858e509e9.PNG)

**Comment by jflesch** [comment]
I'm going to need the [diagnostic output](https://openpaper.work/en-us/helpdesk/kb/1/) after it happens (but before you restart Paperwork)

**Comment by AdnanMuhib** [comment]
Kindly Find Attachment
[diagnostic output.txt](https://github.com/openpaperwork/paperwork/files/1225031/diagnostic.output.txt)

**Comment by jflesch** [comment]
Hm, are you trying to export to a local drive or a remote one ?

**Comment by jflesch** [comment]
OK, reproduced here

**Comment by AdnanMuhib** [comment]
I am trying to save to local drive, not remote drive.

**Comment by jflesch** [comment]
https://github.com/openpaperwork/paperwork-backend/commit/d8fd942a5e847c79808cbcf9631a3397723bb2aa

**Comment by jflesch** [comment]
db586cbc56b259ec2bc83858591f495e06b90405
