### ISSUE TITLE
Epson WorkForce ES-300W - no paper found

### ISSUE THREAD

**Issue by LexiconCode** [openpaperwork/paperwork#667]
I purchased Epson WorkForce ES-300W when I discovered just how crummy software can be. After some research paperwork popped up on my radar. Thank you for your hard work!

When I try to scan, the document is scanned through the scanner as one would expect. Then Paperwork message pops up "Scan Failed: no paper found" In addition the resolution drop-down menu is grayed out. Other Windows applications seem to work as expected.

For your convenience [diagnostics.txt](https://github.com/openpaperwork/paperwork/files/1243920/diagnostics.txt)

Let me know if there's any other information I can provide! Edit: It looks like this is an issue with the backend pyinsane2. You can move the ticket or I can reopen it on pyinsane2 issues.

**Comment by jflesch** [comment]
>  the document is scanned through the scanner as one would expect.

To clarify : Does the scanned image start appearing or the screen, or not at all ?

**Comment by jflesch** [comment]
From what I can see, I would say your driver is having a weird behaviour. It seems it starts by sending an (almost) empty page to Paperwork, before sending the actual page.
Unfortunately, without having the same hardware than you, I don't think I will be able to do much for now.

I'll try to prepare a more advanced diagnostic program at some point, but unfortunately I'm lacking time for it ... :/

**Comment by LexiconCode** [comment]
> To clarify : Does the scanned image start appearing or the screen, or not at all ?
The scanned image does not appear at all.

I'd be willing to set up a test environment that you could remote into for testing.

**Comment by jflesch** [comment]
Sorry for the late reply. I've been working on a test program to get detailed logs when scanning. Hopefully it can collect enough information so I can fix your problem.

The test program is available here: https://openpaper.work/en/scanner_db/#contribute . Can you give it a try please ?
It will do a test scan, generate a report, and automatically upload it to https://openpaper.work/ .

**Comment by jflesch** [comment]
https://github.com/openpaperwork/pyinsane/commit/14f0062b24b442e4b65844efef2811f250093e41

Let's see if this fix works :-)
Can you download and run again the test program please ?
(by the way, one report was enough ;)

**Comment by LexiconCode** [comment]
I apologize for the multiple reports apparently hitting the back button sends another report. Apparently the scanner is very picky about which USB port it's plugged into in terms of functioning. Obviously I had some sort of rate limiting so I'll try again this morning. I'll rerun the diagnostics and attempt utilizing your fix.

**Comment by jflesch** [comment]
Well, at least it goes a little further this time ... :/

**Comment by jflesch** [comment]
Just so you know, it seems that in report [28](https://openpaper.work/en-us/scanner_db/report/28/), it didn't find any scan source at all (no feeder), whereas in report [32](https://openpaper.work/en-us/scanner_db/report/32/) it did find a feeder.
I haven't changed anything in that regard, so I assume it's related to your change of USB port.

**Comment by LexiconCode** [comment]
That is correct.

**Comment by jflesch** [comment]
https://github.com/openpaperwork/ironscanner/commit/1f6406400d34afdb422ac9898e79fec9dc93b821

I've updated the [test program](https://openpaper.work/en/scanner_db/#contribute). Can you give it another try please ?

**Comment by LexiconCode** [comment]
[Done](https://openpaper.work/en-us/scanner_db/report/34/) :)

**Comment by LexiconCode** [comment]
@jflesch Let me know if there's any other information I can provide.

**Comment by jflesch** [comment]
@LexiconCode I've added a little bit of verbose in Pyinsane (there is a call too Seek() with values unsupported at the moment --> I need to know the values). Can you run again [IronScanner](https://openpaper.work/en/scanner_db/#contribute) please ?

**Comment by LexiconCode** [comment]
[Done](https://openpaper.work/en-us/scanner_db/report/79/)

**Comment by jflesch** [comment]
I've updated Pyinsane and the test program based on what your driver requested. [Can you give it another try please ?](https://openpaper.work/en/scanner_db/#contribute)

**Comment by LexiconCode** [comment]
[Done!](https://openpaper.work/en-us/scanner_db/report/80/)

**Comment by jflesch** [comment]
\o/
Thank you for your help and your patience :)

**Comment by jflesch** [comment]
I've modified the report to set `test successful` to `true`

**Comment by jflesch** [comment]
If you want to give it a try with Paperwork:

The builder has already rebuilt Paperwork for Windows with the required fixes: https://download.openpaper.work/windows/amd64/paperwork-master-latest.zip . However the Windows installer is not automatically rebuilt. So, if you want to try, you can simply extract the package manually where you installed Paperwork (default: `C:\Program Files (x86)\Paperwork`).

Note that this package doesn't include Tesseract nor its training files, so I would advise just unpacking and replacing files without deleting anything first. Also I suggest you make a backup copy of `C:\Program Files (x86)\Paperwork` first ;-)

Next release of Paperwork will also include those fixes.
