### ISSUE TITLE
Lost 75% of labels after installing 1.2.1

### ISSUE THREAD

**Issue by lcecic** [openpaperwork/paperwork#672]
Hello

I just have installed version 1.2.1 (I used 1.1.2), and I discover that main of the labels (I would say about 75%) was lost, the color of the label is also change (1 label is black and the others are white).
The remaining label seems to be assigned to the corrects doc.

**Comment by jflesch** [comment]
1) Do you use Windows or Linux ?
2) Can I get [the diagnostic output please](https://openpaper.work/en-us/helpdesk/kb/1/) ?
