### ISSUE TITLE
Is there a way with full command line

### ISSUE THREAD

**Issue by kmkmahesh** [openpaperwork/paperwork#685]
I am searching for a way that i can scan directly without using gui by providing arguments at command line like

device 
pdf or jpg (format)
all pages or multiple pages or single page (page limit)
colour or black 
resolution
save path
ocr (enabled/disabled)

directly from command line.
if anything is there please provide the documentation to me so it can help me better.
Thanks
K Mahesh Kumar

**Comment by jflesch** [comment]
Hello,

Assuming you're running Linux, yes, there is.

The [Sane project](http://sane-project.org/) is the one providing scanner drivers for Linux. They also provide a command called ```scanimage``` : https://linux.die.net/man/1/scanimage . You can use this command to do the scan the way you want it and save it to a temporary directory / file.

You can then use ```paperwork-shell import``` to import the file written by scanimage (see ```paperwork-shell --help``` and ```paperwork-shell help import``` for more details).

Best regards,

**Comment by kmkmahesh** [comment]
thanks i will search them i will update you back

**Comment by tYYGH** [comment]
@kmkmahesh Paperwork can import images. You do not _have_ to have a PDF.
If you do want a PDF, then `convert` can do that for you ;-)

**Comment by jflesch** [comment]
Tesseract can also generate directly PDF files. There is a config file called 'pdf' for that purpose. However I'm not sure whether it really works or not. Last time I tried I wasn't able to make it work.

**Comment by kmkmahesh** [comment]
@tYYGH Even paperwork wont support all arguments through command line 
@jflesch there is no info about pdf creating using Tesseract it is only for OCR 

If any one has any info regarding my issue please provide
Thanks,
K Mahesh Kumar

**Comment by jflesch** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#how-do-i-produce-searchable-pdf-output

**Comment by jflesch** [comment]
I'm closing this issue. It is unrelated to Paperwork.
