### ISSUE TITLE
ValueError: Namespace Notify not available

### ISSUE THREAD

**Issue by tsjfd** [openpaperwork/paperwork#688]
I want to give paperwork a try. I hack `docker run -ti --rm -e DISPLAY=$DISPLAY -e XAUTHORITY=$HOME/.Xauthority -e HOME=$HOME -e USER=$USER -v $HOME:$HOME -v /tmp/.X11-unix:/tmp/.X11-unix -v /etc/sane.d/:/etc/sane.d/ tclavier/paperwork` into the console as described at https://github.com/openpaperwork/paperwork/blob/unstable/doc/install.docker.markdown and get:

```
+ exec su gh -c 'cd /home/gh;  paperwork'
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 7, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python3.5/dist-packages/paperwork/paperwork.py", line 29, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```
I am running Ubuntu 16.04.

**Comment by jflesch** [comment]
@tclavier / @scubbx  : ping ?

**Comment by jflesch** [comment]
[Flatpak support](https://github.com/openpaperwork/paperwork/tree/unstable/flatpak#readme) is pretty much ready. So unless @tclavier or @scubbx decide to keep supporting Docker, I think it will be dropped at the next release of Paperwork

**Comment by jflesch** [comment]
Docker support is going to be dropped.

**Comment by jflesch** [comment]
Docker support has been dropped in branch 'develop' (future 1.3): 0a521873b0b624e00b232a541380e2ab2702c300

**Comment by jflesch** [comment]
@tsjfd : You may want to try the Flatpak version : https://github.com/openpaperwork/paperwork/blob/master/flatpak/README.markdown
