### ISSUE TITLE
[flatpak] OCR fails

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#697]
[paperwork_diag.txt](https://github.com/openpaperwork/paperwork/files/1454446/paperwork_diag.txt)

**Comment by jflesch** [comment]
35fa1d2ad2bb08716a49d22e4fa3cbec10b82f71

**Comment by Moini** [comment]
Is this released yet?

**Comment by jflesch** [comment]
Did you install the version 'master' or the version '1.2.2' specifically ?

**Comment by jflesch** [comment]
hm, actually, the fix of this ticket is in both versions. So it should work.
As for #721, can you do another run and get the [diagnostic output](https://openpaper.work/helpdesk/kb/1/) please ? (do not restart Paperwork between both)
