### ISSUE TITLE
Where is the back-end code

### ISSUE THREAD

**Issue by gkzsolt** [openpaperwork/paperwork#706]
Hi,

I installed openpaperwork a few days ago and wanted to take a peek at the back-end code. However, I cannot find it. The wiki says 'frontend' and 'backend' in src but there is no 'backend'. Where can I find it?

Thanks,
  Zsolt

**Comment by jflesch** [comment]
https://github.com/openpaperwork/paperwork-backend

**Comment by gkzsolt** [comment]
Thanks ;)
