### ISSUE TITLE
Openpaper.work design / look&feel is bad

### ISSUE THREAD

**Issue by jflesch** [openpaperwork/paperwork#707]
I'm obviously not a good web designer.
If someone feels like they can do better than me regarding https://openpaper.work / https://github.com/openpaperwork/openpaper.work , please feel free to do it :)

**Comment by mjourdan** [comment]
Hi! I gave it a shot : http://mjourdan.frama.io/paperwork-pages/

**Comment by jflesch** [comment]
Nice :)
I'll try to create Django templates based on it

**Comment by mjourdan** [comment]
As GNOME is hosting it's own Gitlab instance, I thought it could be interesting to use [Gitlab pages](https://about.gitlab.com/features/pages/) to host the page. The site is automatically built each time I push to the repo, that's cool! To build the site, I first look at Pelican (as it is written in Python) but could not find any theme appropriate. So I tried with Middleman, which is written in ruby (which doesn't not matter much unless you are concerned with software dependencies I guess). For the UI, I simply used [something existing](https://middlemanapp.com/). I didn't thought much about the text, and the screenshots clearly don't match our purpose. That's all for the feedback.

I guess with Django you would have to keep self-hosting at least, also, I have no idea of the effort required to port the theme.

**Comment by jflesch** [comment]
Gitlab sounds like a good idea, but I'm not sure it would be so easy. While openpaper.work looks static, it isn't. There is the statistics collection mechanism hosted on it.
I guess we could split the website from the statistics collection, but then there is also an issue regarding the HTTPS certificate: For good placement in search engine results, nowadays, the website should be available using HTTPS. --> I'm using Let's Encrypt --> To get certificate with Let's Encrypt, I need control over the server hosting the website.

However, Django can serve static content. And running a cronjob nightly to update the website from a Git repository shouldn't be too much work :)
I guess it would be the easiest way to go.

@mjourdan : Can I have access to the sources please ? BTW, [Openpaper.work](https://github.com/openpaperwork/openpaper.work) is currently GPLv3, is this license ok for you ? (currently I'm the only author for openpaper.work so I can still change the license easily).

**Comment by jflesch** [comment]
Yep, you're right the Affero would make more sense. I'll change it.

**Comment by jflesch** [comment]
Switched to AGPL: https://github.com/openpaperwork/openpaper.work/commit/ae2891e69a38da1eb9c860da337a6913898e71d8

**Comment by jflesch** [comment]
Note to myself: http://colorschemedesigner.com/csd-3.5/ (I'll probably adjust a little bit the colors)

**Comment by jflesch** [comment]
I had a look yesterday. I think mixing Middleman and Django is likely to be a huge complicated mess. I think I will just try to reuse/rewrite the HTML/CSS/JS as Django templates.

**Comment by jflesch** [comment]
@mjourdan [Here is my shot at it (based on yours)](https://jflesch.kwain.net/~jflesch/openpaper.work/). What do you think of it ?

**Comment by jflesch** [comment]
It's live: https://openpaper.work/

**Comment by mjourdan** [comment]
Not sure about the robotic arm, but overall I like it very much! The folder and blueprint illustrations are really, really good!

**Comment by jflesch** [comment]
Yeah, I'm not really proud of the arm. I guess I'll have to re-make it later at some point.
Anyway, it seems we are both ok with this design, so I can close this ticket :-)
Thank you very much for your help :-)
