### ISSUE TITLE
All labels are assigned to a new document

### ISSUE THREAD

**Issue by gkzsolt** [openpaperwork/paperwork#709]
When I create a new document by scanning pages, ***all***  existing labels are automatically assigned to it. It is very tedious to uncheck them, plus this task grows 0(n) with the number of labels ;)

**Comment by jflesch** [comment]
Yeah, it's a bit dumb when you start, but it should start learning after ~20 documents :-)
I guess it could be improved by not adding labels at all automatically on the ~20 first documents.

**Comment by gkzsolt** [comment]
And maybe have the option to turn this Off/On... ;)

**Comment by lorenzhs** [comment]
Do you mean 20 documents per label? Because there are a few labels (with rather few documents associated with them) that are assigned to *all* new documents, and I have close to 200 documents now :(

**Comment by gkzsolt** [comment]
I have "only" ~30 documents, but each time a scan a new document, it "guesses" and sticks 17 labels to them (there are 22 labels in total). The labels don't have anything in common with the document: now I scanned an invoice, with only a few words, totally unrelated. So it seems this Simple Bayes algorithm is far from perfect.
After _lorenzhs_'s comment, I am not expecting this to improve dramatically after some new scans. So I'd opt for a boolean/checkbox option, like `--dont-guess-labels`. I didn't know there is a shell version of paperwork, and I don't see this `--no_label_guessing` option (just a `guess_labels` command). But anyway, I am using the GUI version. Would it be difficult to put a "Do not guess labels" settings flag?
Otherwise the app can become quite unusable after some time.

**Comment by jflesch** [comment]
@gkzsolt Hm, let's try something first. Can you stop Paperwork, run `rm -rf ~/.local/share/paperwork` and restart it ? It will force Paperwork to rebuild to the index, but also retrain de Bayesian filters. If it makes things better, it means there is a bug regarding the way Bayesian filters are trained.

**Comment by gkzsolt** [comment]
I did this test, and then scanned a 4 pages document. It assigned only 1 label to it. I don't know if this is optimal or not, but definitely better than previous behaviour (the invoice did not gave labels, which is correct.)

**Comment by jflesch** [comment]
I think that means I need to improve [the simulations I used to test the Bayesian filter training](https://github.com/openpaperwork/paperwork/tree/master/scripts) ... :/

**Comment by lorenzhs** [comment]
Thanks, deleting the index and restarting paperwork did the trick for me. The automatically added labels are quite useful now, thank you!

**Comment by jflesch** [comment]
Note to myself: The problem may come from the untraining/retraining of the filters when documents are modified (for instance when a new page is scanned). For the untraining part, the text should be what it was when it was trained, not what it is now (can be found back in the index). Problem is similar when a document is deleted.

**Comment by jflesch** [comment]
Ok, so .. while making a workaround regarding Python GIL a while ago, it seems I pretty much broke 
the untraining/retraining of the filters :(

Fixed: 178312c78a6c0f4f5cfe8a924305ababa900754f

The fix should be even cleaner than what was done before. The exact text content used for untraining/training is now more precise. The drawback is that the index has to keep a copy of all the text content so we can use it for untraining when a document has been modified or deleted.

I'm going to do some more tests so I'll keep this ticket opened for now.

**Comment by jflesch** [comment]
Ok, looks good to me. 1.2.4 is ready to roll :-)
