### ISSUE TITLE
Cannot import new files

### ISSUE THREAD

**Issue by Moini** [openpaperwork/paperwork#724]
When I click on 'Scan v' > import file(s), I get the following error (no crash, but also nothing happens):

```
INFO   paperwork.frontend.mainwindow  Import: ['file:///media/somedir/mydocs']
INFO   paperwork.frontend.mainwindow  Adding file:///media/somedir/mydocs to recently used files
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/__init__.py", line 1701, in _do_import
    file_uris, self.__main_win.doc)
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/docimport.py", line 496, in get_possible_importers
    if importer.can_import(file_uris, current_doc):
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/docimport.py", line 235, in can_import
    for child in self.fs.recurse(parent):
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/fs.py", line 448, in recurse
    parent = Gio.File.new_for_uri(url)
NameError: name 'url' is not defined
ERROR  paperwork.frontend.diag        ===========================

```

flatpak from https://builder.openpaper.work/paperwork_master.flatpakref, on Linux Mint 18.3

**Comment by jflesch** [comment]
Argh sorry ... I made my previous fix far too fast and it actually made things much worst ... :/ (I really need to spend more time on automated tests ....)
New fix: https://github.com/openpaperwork/paperwork-backend/commit/197b490000895ab35afaa93a9ca252bc6ca709f7 (I tested it a bit further this time ;)

**Comment by Moini** [comment]
Thanks again :) (and happy holidays!)

The good news is that it does indeed seem to do the scanning now. The bad news is that it eats up almost all of my RAM until other applications misbehave and I've got to kill it before it's done.

Would it be possible to free up resources after a file has been processed?

Attaching log.
[paperwork_log.txt](https://github.com/openpaperwork/paperwork/files/1588079/paperwork_log.txt)

**Comment by jflesch** [comment]
Interresting. I did my last test with 570 pdfs. But most of them included text (so no OCR). So based on what you just told me, it means there is a memory leak when OCR is used. I'll open another ticker for that.

BTW, how much RAM do you have ?

**Comment by Moini** [comment]
16GB ( > 11 were occupied by paperworks, and I had a virtualbox instance running, which was undisturbed, fortunately :) - but mail encryption broke... and worked again after paperworks was killed.).
