### ISSUE TITLE
Difference between Paperwork and Paperless

### ISSUE THREAD

**Issue by Erwyn** [openpaperwork/paperwork#731]
Hello,

I'm currently looking for the kind of solution that you are providing here. I've also encountered another one called Paperless here: https://github.com/danielquinn/paperless .

Is the only difference that one is web based and the other one is desktop based?

I have the feeling that paperwork is doing much more, but it's not clear in my head.

Anyway, thanks for your time and for your hard work.

Best Regards,
Martin

**Comment by jflesch** [comment]
In Paperwork, there is a strong emphasis on image scanner support (device support, automatic orientation detection, export as PDF with OCR included, etc). It is also designed to be as easy as possible to use (therefore installing and configuring a web server is not an option).

Paperless cannot use image scanners (browsers provide no access to image scanner). However it has the advantage of being a web interface, making it easier to access from anywhere (home, work, travel, etc).

I personally use [Syncthing](https://syncthing.net/) to synchronize my documents between all my computers (work included) but I assume this solution can't work for everybody.

**Comment by jflesch** [comment]
Note that there are also other small differences.

For instance, in Paperwork, documents have no title. They just have a date, labels, and optionnally some extra keywords (I personally never use the extra keywords). The filenames of the input files don't matter. Paperwork uses Bayesian filters to automatically try to learn from you and set labels.

Paperless chose a more manual approach: It also supports labels (aka tags), and let you define ["matching algorithms"](https://paperless.readthedocs.io/en/latest/guesswork.html#how-do-i-set-up-these-matching-algorithms) to set them automatically.

**Comment by Erwyn** [comment]
Thanks for your quick and complete answer!

was the issue #552 a proposal to port paperwork in the cloud in a paperless way or was it only targeting the storage of the documents but not the interface/computing?

**Comment by jflesch** [comment]
One or the other, both would be good. The problem is how much time someone would be willing to spend on it.

**Comment by Erwyn** [comment]
Yeah sure, it's definitely a lot of work. Porting it to the web would however mean dropping the scanner support and upload JPGs / PDFs / whatever right?

**Comment by jflesch** [comment]
Not really.

What I had in mind was:
- create a web interface (similar to Paperless)
- put a REST API on it (similar to Paperless)
- turn Paperwork into a desktop client for the web interface (similar to what Thunderbird does with IMAP)

It would be like using a Gmail account with Thunderbird: You have your client on your machine (not just in the browser), that can access scanners and browse documents faster. But you also have a web interface to access your documents when you're far away from home.

With this approach you can have the best of both world. But it's a *lot* more work.

**Comment by Erwyn** [comment]
Where would the computation be done in this scenario? I suppose on the server side as you need the same to be accessed through the web api. Am I wrong?

In this scenario, what would be doing the desktop client? Downloading the document and taking care of the automagic connection to your scanner, scanning and uploading to the server?

**Comment by jflesch** [comment]
I guess everything that could be done server-side should be done server-side.

The thing is, I also want to keep the current way Paperwork works: standalone (again, I want my mother to be able to install and use it if she wants ;).
But there is an easy way to get both modes without duplicating code: the server could be packaged with Paperwork. If you want it standalone, it can start simply start a server locally everytime it's started, and stop it when it stops.

**Comment by Erwyn** [comment]
Yes you could definitely have it as a local server. This means you would probably have something like 3 components:

* The Server
* The Web Interface
* The Desktop Interface

Interesting.

**Comment by Erwyn** [comment]
Okay, I'm taking advantage of this thread for two-three more questions:

* If I get correctly what Paperwork is doing, it tags automatically the documents, or at least learns from you how to tag and then repeat it, and let you search through the text in your document, those are the main feature right?

* If I put let's say my payslips in it, I can then search via the "payslip" label and search for the date in the document?

* If we dream of having the Server/Web Interface/Desktop Interface architecture. Is the current code base re-usable or is it like starting from scratch? If so, would we still use Python then?

**Comment by jflesch** [comment]
> If I get correctly what Paperwork is doing, it tags automatically the documents, or at least learns from you how to tag and then repeat it, and let you search through the text in your document, those are the main feature right?

Yes

> If I put let's say my payslips in it, I can then search via the "payslip" label and search for the date in the document?

You can search by keywords (OCR), labels, or by date.

The dates in the documents have various formats and OCR may fail on them, so Paperwork doesn't extract them automatically (yet :).

> If we dream of having the Server/Web Interface/Desktop Interface architecture. Is the current code base re-usable or is it like starting from scratch? If so, would we still use Python then?

I think most of the code changes would be in [paperwork-backend](https://github.com/openpaperwork/paperwork-backend). Except for the network settings, I see no reason to change the frontend part. 
Python would still be the main language used, therefore I guess Django would be the default choice server-side.

In the long term, I will just switch the libraries PyOCR, Pyinsane and libpillowfight to pure C (and therefore rename them "libocr" and "libinsane") and make GObject introspection bindings for them. This will allow to use them from any programming language.
