### ISSUE TITLE
When a label is deleted the index is not refreshed

### ISSUE THREAD

**Issue by deliantwo** [openpaperwork/paperwork#734]
Steps to reproduce:
1. Assign a label to a document
2. Edit the document
3. Remove the label using the trashbin button
4.The documents list shows the deleted label

Editing the document and going back again to the index solve the issue.

**Comment by deliantwo** [comment]
Sure, here the diagnostic output. Let me know if you need more information. The name of the label I've removed is "Condominio". I've done the following steps:
1. Edit a document with a label already present on another document
2. Delete the label "Condominio"
3. The documents list is still showing the label 
[paperwork_734.txt](https://github.com/openpaperwork/paperwork/files/1627400/paperwork_734.txt)

**Comment by jflesch** [comment]
Here is the first clue regarding your problem:

```
INFO   paperwork.frontend.mainwindow.docs Label Color: #000000 ; Text: Condominio must be deleted. Applying changes
ERROR  paperwork.frontend.util.jobs   ===> Job LabelDeleter:0 raised an exception: <class 'TypeError'>: 'NoneType' object is not iterable
ERROR  paperwork.frontend.util.jobs    0: /usr/lib/python3.6/site-packages/paperwork/frontend/util/jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: /usr/lib/python3.6/site-packages/paperwork/frontend/mainwindow/docs.py: L  352: do
ERROR  paperwork.frontend.util.jobs    2: /usr/lib/python3.6/site-packages/paperwork_backend/docsearch.py: L  430: destroy_label
ERROR  paperwork.frontend.util.jobs   ---> Job LabelDeleter:0 was started by:
ERROR  paperwork.frontend.util.jobs    0:   /usr/bin/paperwork: L   11: <module>
ERROR  paperwork.frontend.util.jobs    1: /usr/lib/python3.6/site-packages/paperwork/paperwork.py: L  189: main
ERROR  paperwork.frontend.util.jobs    2: /usr/lib/python3.6/site-packages/paperwork/paperwork.py: L  174: main
ERROR  paperwork.frontend.util.jobs    3: /usr/lib/python3.6/site-packages/gi/overrides/GLib.py: L  585: run
ERROR  paperwork.frontend.util.jobs    4: /usr/lib/python3.6/site-packages/paperwork/frontend/util/dialog.py: L   59: _ask_confirmation_goto_next
ERROR  paperwork.frontend.util.jobs    5: /usr/lib/python3.6/site-packages/paperwork/frontend/mainwindow/docs.py: L  586: _do_delete
ERROR  paperwork.frontend.util.jobs    6: /usr/lib/python3.6/site-packages/paperwork/frontend/util/jobs.py: L  256: schedule
```

However I'm not sure how it could happen :/

**Comment by jflesch** [comment]
Ok got it: https://github.com/openpaperwork/paperwork-backend/commit/9fc2755b7fa3467b6cd883b1d63879eb0046c2ce

I haven't had time to test this fix yet. I may not have this week-end.
Anyway, if you want to try it, it should be available in the [next nightly flatpak](https://github.com/openpaperwork/paperwork/blob/master/flatpak/README.markdown#readme) (in other words, in one day or two depending on your timezone)

**Comment by jflesch** [comment]
Appears to be fixed
