### ISSUE TITLE
Indexes are created in a strange location

### ISSUE THREAD

**Issue by JoshuaPK** [openpaperwork/paperwork#738]
I think it's great that we can configure the location of the document store.  However, if I have a repository of 10,000 documents, it should not have to reindex those documents every time I move it around.  To me, the ability to copy and move around the data directory should mean that the data directory contains everything- documents, indexes, tag guesses, and anything else.

I've spent the past couple of hours stepping through the code to see exactly WHEN that index directory is set to ~/.local/share/paperwork, and how I might be able to set it to the directory containing the document store.  Where is this index directory set?

**Comment by JoshuaPK** [comment]
I found the assignment of the index location variable in docsearch.py.  Next I need to see if the document location is available at that point.  Before I create a pull request, I should ask, is there a reason that the index should reside under the ~/.local/share directory, aside from LSB convention?  I noted that the Flatpack initialization code does the same thing.  Is there a reason that it is not desired to keep the indexes with the documents?

**Comment by jflesch** [comment]
>  Is there a reason that it is not desired to keep the indexes with the documents?

Yes:
* When you use a synchronisation program (like Syncthing, Sparkleshare, or Nextcloud), you don't want to synchronize the whole index every time a minor change happen
* When you backup, you don't want to backup the index. It's useless.

Basically, the index is seen here as temporary data. I even wonder if it wouldn't be best to put it in ~/.cache.

Just so you know, there is already this ticket opened: #619

**Comment by JoshuaPK** [comment]
Ok, I'll close this and discuss further on #619
