### ISSUE TITLE
Impossible to change an image to text with the Paperwork's OCR

### ISSUE THREAD

**Issue by aldobelus0** [openpaperwork/paperwork#739]
Hi. I have installed Paperwork at a GNU, Solus OS, 3 version. I can't make work the OCR side of the program. I don't know what to do more. 

I have a PDF with a text as image (I hate them!). I run the OCR to extract the text from it. The words from the text, I can see them as plain text when I hover them with the cursor (as you can see at the image below), but it's impossible to send the whole document after, as text, plain or rich, to any place. When I try to export the document, there's no change, the exported document is the same one -is an image- as the previous I've entered to Paperwork. Nothing is changed, I want to mean... 

So, there's an OCR in Paperwork or not? It's me, that I'm doing it wrong? Why I can't send the document as plain text to anywhere? Did I lost some? 

Can you help me, please? Thanks. 

![The words change, but nothing more](https://user-images.githubusercontent.com/15985449/35060020-5d0df7b4-fbbd-11e7-9d2e-b5d2b072cc06.png)

**Comment by jflesch** [comment]
Actually, currently, Paperwork has for rule to never modify the PDF files. So if you imported a PDF and export it, it will simply give you back the original PDF. That's made on purpose (to keep metadatas, like numeric signature for instance).

Now, that's a feature that could be added easily in a future release.

**Comment by aldobelus0** [comment]
So, do you want to mean that the feature of OCR doesn't exist, there is not such thing at Paperwork? Or, in other words, how works the OCR in Paperwork? Only with images?

**Comment by jflesch** [comment]
Implemented in the branch `develop`: https://github.com/openpaperwork/paperwork-backend/commit/067d3a994f225773a1cc137d03f7b1d03da57a9f
Will be available in the [next nightly Flatpak build](https://github.com/openpaperwork/paperwork/blob/master/flatpak/README.markdown#nightly-builds) (around 2018/01/18 at noon (UTC+1))

**Comment by aldobelus0** [comment]
**Thank you very much, Jerome**. That you wrote means that will be a OCR export feature at Paperwork soon? I will love it! Unfortunately, can be too late for me... But I'm grateful for your answers and the developing action.

(I'm a little bit desperate. I've installed SolusOS and, apparently, there's not an OCR program at its repo :-( , and I have no previous experience at compiling... but I will try!). 

Greetings!

**Comment by jflesch** [comment]
> soon

Hmmm, yeah, depends what you mean by "soon" :-/

Currently, my effort are mostly focuses on [improving scanner support](https://github.com/jflesch/ironscanner) (this is going to take a while). Then there will be a bug fix version of Paperwork, 1.2.3. Then only I will work on 1.3 and later release it (again, it's going to take a while).
So .. yeah, not so soon.

It's actually one of the reasons I'm making nightly Flatpak builds of the branches `master` and `develop`: So people who want to test or just have these new features can. [Flatpak appears to be supported on SolusOS](https://flatpak.org/getting.html) so you can try it if you want.

**Comment by aldobelus0** [comment]
So, if I install Paperwork from Flatpack now, can I have the OCR feature to export PDF documents or images in plain or enriched text? I already have installed Flatpack, to test it...

**Comment by jflesch** [comment]
If you install Paperwork with Flatpak *tomorrow* and specifically install the branch *develop*, then yes, you will have the feature. (tomorrow only becayse the nightly build hasn't been run yet)

**Comment by aldobelus0** [comment]
Thank you very much... again! _Hooray_ for the free software!! xD I'll do as you tell me!
