### ISSUE TITLE
Brocken download link

### ISSUE THREAD

**Issue by sbrunner** [openpaperwork/paperwork#745]
On this page
https://openpaper.work/fr/
the linux dowload point here:
https://github.com/openpaperwor//paperwork/#installation
but it should be:
https://github.com/openpaperwork/paperwork/#installation
a 'k' is missing ...

**Comment by jflesch** [comment]
Fixed:
https://github.com/openpaperwork/openpaper.work/commit/09b107aa6bd3f1bc2e90a701471203d09c6d4b84
https://github.com/openpaperwork/openpaper.work/commit/96ba9b73ac13e91de75e3ff2c2124243d4dfdc67

Thanks for taking the time to report it :)
