### ISSUE TITLE
[Windows]Can't attach multiple labels to a document

### ISSUE THREAD

**Issue by simpey84** [openpaperwork/paperwork#746]
I installed Paperwork 1.2.2 on my computer with Windows 10.

I imported my first documents.

I have created and associated labels with these documents.

When I try to associate a second label with a document, this status is not saved: the second label is never associated with the document and the first label loses its color to become white...

I've tried to uninstall and resinstall with the admin permissions, but that doesn't change anything!

**Comment by jflesch** [comment]
Can you reproduce the problem and then get the [diagnostic output](https://github.com/openpaperwork/paperwork/wiki/Getting-the-diagnostic-output) please ?

**Comment by simpey84** [comment]
I just tried on another computer with a very similar hardware (windows 10 too). It's the same thing. I can't link two labels to a document and the color becomes white.

Here is the diagnostic result:
[paperwork-diag_180131.txt](https://github.com/openpaperwork/paperwork/files/1683583/paperwork-diag_180131.txt)

**Comment by jflesch** [comment]
Reproduced

**Comment by jflesch** [comment]
Reproduced on Windows but not Linux

**Comment by jflesch** [comment]
Fix: https://github.com/openpaperwork/paperwork-backend/commit/8ba278f6b6b271fcbc216f5fdb2d9677ebd6599e

This is one nasty bug. I'll to a release asap.

**Comment by jflesch** [comment]
I've release [Paperwork 1.2.3](https://openpaper.work/). It should take care of this problem.

**Comment by simpey84** [comment]
Installed and tested, it looks perfect!
However, the link doesn't seem to be updated on the home : https://openpaper.work/fr/
I used : https://github.com/jflesch/paperwork/releases/download/1.2.3/paperwork_1.2.3_win64_installer.exe

**Comment by jflesch** [comment]
Oops, sorry, I forgot the French translations. I've fixed it. It won't happen again: https://github.com/openpaperwork/openpaper.work/commit/8587a2154c3e364629856b36530506a37bf5e868
