### ISSUE TITLE
Command 'make version' first

### ISSUE THREAD

**Issue by Maier123** [openpaperwork/paperwork#753]
Hello, 
when running the setup.py file, I get the Error messages from line 24 and 25, the _version.py file is missing and I should run the 'make version' command first. Can someone tell me what exactly to put in the command prompt? Or am I supposed to do something else? I could create a file '_version.py' but it wouldn't have anything in it, obviously.
Thanks

**Comment by jflesch** [comment]
Which version do you want to install ? The latest released version or the one currently in the branch 'master' of Github ?

**Comment by jflesch** [comment]
Instructions for the latest release: https://github.com/openpaperwork/paperwork#installation
Instructions for the versions currently in preparation in Github: https://github.com/openpaperwork/paperwork/blob/master/doc/install.devel.markdown << unfortunately at the moment this is not up-to-date. I will update it
