### ISSUE TITLE
Paperwork uses 100% CPU

### ISSUE THREAD

**Issue by Terminalator** [openpaperwork/paperwork#754]
As requested, opening an issue here.

Sometimes when I hover my mouse over the "copy selected text" icon in the top right corner, my cpu usage goes to 100% and stays there. The text box "copy selected text" blinks every time I move my mouse over the document but the cpu always stays at 100% until I exit the program.

Note, I have NO scanners attached to my computer; I imported a few test documents to see how things work, before using it on all my documents.

[paperwork.txt](https://github.com/openpaperwork/paperwork/files/1742352/paperwork.txt)

![paperwork system monitor](https://user-images.githubusercontent.com/19365728/36455682-1d6ed028-1699-11e8-9a4b-94ed8c61bdd7.png)

**Comment by toerb** [comment]
Hi all,
I can reproduce this issue with Arch Linux, too.
You don't even have to select some text.
Just hovering above the "copy selected text" box brings one cpu up to 100 %.
The cpu load stays until you close this screen for example by opening another document.

**Comment by jflesch** [comment]
124ca47fd2a05a1aa87d24fa3f3a9332f0838897

**Comment by jflesch** [comment]
Thanks for reporting this issue. It was actually a stupid mistake from me (as most of the bugs in Paperwork .. :-). It's fixed.
