### ISSUE TITLE
importing folder and duplication 

### ISSUE THREAD

**Issue by icf20** [openpaperwork/paperwork#755]
https://github.com/openpaperwork/paperwork/wiki/File-import

so if today i import a folder dont delete the source files and next day i import the same folder again because i got new files scanned 

do i get duplicate files on my papers folder or not ?

**Comment by jflesch** [comment]
If the files are PDF, then no. Paperwork detect duplicate PDFs and doesn't import them.
However it doesn't detect duplicate images (mostly due to an internal limitation).

**Comment by icf20** [comment]
nice !
