### ISSUE TITLE
Resolution setting unavailable

### ISSUE THREAD

**Issue by icf20** [openpaperwork/paperwork#760]
i am looking for a way to limit the scan to 600 DPI instead of the max 1200 DPI is there any way to do it because the PDF are huge, a A4 pdf is ~8mb

**Comment by jflesch** [comment]
This setting should be available in the settings dialog: https://github.com/openpaperwork/paperwork-screenshots/blob/master/1.0/settings.png

**Comment by icf20** [comment]
hmm what do i do if that option is disabled ?

**Comment by jflesch** [comment]
Then it's a bug.

Can you please:
* Start Paperwork
* Open the settings dialog
* Wait for it to load (or to try to load)
* Close it
* [Application menu --> Advanced --> Diagnostic](https://github.com/openpaperwork/paperwork/wiki/Getting-the-diagnostic-output)
* Save the diagnostic in a file, and attach the file to this ticket
?

**Comment by icf20** [comment]
this log is from a windows 7 machine

```
INFO   paperwork.frontend.settingswindow Sources found: ['0001\\Root\\Flatbed']
WARNING paperwork.frontend.settingswindow No translation for source [0001\Root\Flatbed]
INFO   paperwork.frontend.settingswindow Got all the sources
INFO   paperwork.frontend.settingswindow Looking for resolution of device [{6BDD1FC6-810F-11D0-BEC7-08002BE2092F}\0001]
WARNING pyinsane2.wia.abstract         Constraint found on property [sti_driver_version] but property not found
WARNING pyinsane2.wia.abstract         Constraint found on property [sti_driver_version] but property not found
WARNING pyinsane2.wia.abstract         Option 'current_intent' preset to 'image_type_color,maximize_quality' on ['EPSON Perfection V37/V370 #2' (EPSON, EPSON Perfection V37/V370, scanner,streaming_video)]
WARNING pyinsane2.wia.abstract         Constraint found on property [sti_driver_version] but property not found
WARNING pyinsane2.wia.abstract         Option 'format' preset to 'bmp' on ['EPSON Perfection V37/V370 #2' (EPSON, EPSON Perfection V37/V370, scanner,streaming_video)]
WARNING pyinsane2.wia.abstract         Failed to pre-set option 'preferred_format' on ['EPSON Perfection V37/V370 #2' (EPSON, EPSON Perfection V37/V370, scanner,streaming_video)]
WARNING pyinsane2.wia.abstract         Constraint found on property [sti_driver_version] but property not found
WARNING pyinsane2.wia.abstract         Option 'depth' preset to '24' on ['EPSON Perfection V37/V370 #2' (EPSON, EPSON Perfection V37/V370, scanner,streaming_video)]
INFO   paperwork.frontend.settingswindow Resolutions found: (50, 100)
ERROR  paperwork.frontend.util.jobs   ===> Job ResolutionFinder:0 raised an exception: <class 'IndexError'>: tuple index out of range
ERROR  paperwork.frontend.util.jobs    0: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\util\jobs.py: L  180: _run
ERROR  paperwork.frontend.util.jobs    1: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\settingswindow\__init__.py: L  273: do
ERROR  paperwork.frontend.util.jobs   ---> Job ResolutionFinder:0 was started by:
ERROR  paperwork.frontend.util.jobs    0: paperwork_launcher.py: L   11: <module>
ERROR  paperwork.frontend.util.jobs    1: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\paperwork.py: L  189: main
ERROR  paperwork.frontend.util.jobs    2: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\paperwork.py: L  174: main
ERROR  paperwork.frontend.util.jobs    3: site-packages\gi\overrides\GLib.py: L  572: run
ERROR  paperwork.frontend.util.jobs    4: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\settingswindow\__init__.py: L  910: on_finding_end_cb
ERROR  paperwork.frontend.util.jobs    5: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\util\actions.py: L   85: on_combobox_changed_cb
ERROR  paperwork.frontend.util.jobs    6: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\util\actions.py: L   64: __do
ERROR  paperwork.frontend.util.jobs    7: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\settingswindow\__init__.py: L  523: do
ERROR  paperwork.frontend.util.jobs    8: site-packages\paperwork-1.2.3-py3.4.egg\paperwork\frontend\util\jobs.py: L  256: schedule
INFO   paperwork.frontend.settingswindow Got value [['0001\\Root\\Flatbed', '0001\\Root\\Flatbed']]
```

**Comment by jflesch** [comment]
Hm, I see the problem, but I'm a bit surprised. It seems your scanner says it can only support resolutions from 50dpi to 100dpi ? It seems really low.
Can you try running 'xsane' (it's another scan program) and tell me what resolutions it says your scanner actually supports please ?

**Comment by jflesch** [comment]
Oh wait, you're under Windows

**Comment by jflesch** [comment]
Let's do that differently: Can you run the test program [IronScanner](https://openpaper.work/en-us/scanner_db/#contribute) and submit a test report please ? (IronScanner allows to send a test report even if the test has failed)

**Comment by icf20** [comment]
the range goes from 50 to 12800

but iron scanner only show  50 75 100

**Comment by jflesch** [comment]
I've updated [IronScanner](https://openpaper.work/en-us/scanner_db/#contribute) to get more info in the traces. Can you download and run it again please ?

**Comment by icf20** [comment]
donw

**Comment by jflesch** [comment]
Hmm, it seems Pyinsane ignored some data it shouldn't have ignored.
I've updated again Pyinsane+[IronScanner](https://openpaper.work/en-us/scanner_db/#contribute). Can you try it again please ?
(there will probably be one more round after this one)

**Comment by jflesch** [comment]
For the record, changes are currently: https://github.com/openpaperwork/pyinsane/commit/5cb11337a5877d841054133dd50cf9377314fdfa , https://github.com/openpaperwork/pyinsane/commit/3f859fdc1fe95963aeb8d5fa00f6f9eebb528f3a

**Comment by icf20** [comment]
ironscanner dint let me change the resolution now it "stuck" at 50

**Comment by jflesch** [comment]
Doesn't matter, I just need the traces in the report for now (test successful or not)

**Comment by jflesch** [comment]
https://github.com/openpaperwork/pyinsane/commit/fb88aaa5f603faad86bd652b89c6c352a4eb573f
https://github.com/openpaperwork/pyinsane/commit/c25134508de9a93dc71d331731556e7dc1e45c13

Ok, it should work this time. Can you try again with IronScanner please ?

**Comment by icf20** [comment]
ironscanner let me pick 1150 top :smile_cat:

**Comment by jflesch** [comment]
Meh, close enough. In the coming months, I'm going to rewrite Pyinsane from scratch anyway .. :)

**Comment by jflesch** [comment]
By the way, scanning still works right ? I haven't broken anything else ?

**Comment by icf20** [comment]
yep scanning works

**Comment by jflesch** [comment]
Awesome, thanks :)
I'm building a version of Paperwork including the fix.

**Comment by jflesch** [comment]
You can get a version of Paperwork with the fix here : https://download.openpaper.work/windows/amd64/paperwork-master-latest.zip .
Unfortunately, I can't build the installer automatically yet. So you will have to manually extract the content of the archive where you installed Paperwork (by default, `c:\Program Files(x86)\Paperwork`).

Thanks for taking the time to report this issue and helping me to fix it :)
Feel free to comment again on this ticket if you have any other issue with your Scanner and Paperwork.
