### ISSUE TITLE
[FlatHub] Flatpak of paperwork 1.2.4 unavailable

### ISSUE THREAD

**Issue by mjourdan** [openpaperwork/paperwork#766]
I recently browsed the mailing list and discovered Paperwork 1.2.4 had been released. No update was available from flathub.

```
$ flatpak info work.openpaper.Paperwork
Ref: app/work.openpaper.Paperwork/x86_64/stable
ID: work.openpaper.Paperwork
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-02-04 13:53:33 +0000
Subject: Fix back the branch name to 'stable' (491d5aca)
Commit: f766b301c2ce30dce580878a0c1d385cbbc7d7206299ed35cd75e44cc0f9d242
Parent: 89d5e2a513f63afeb732a8a29ce9c946d996b0e1d0b45b2485cc6d180a753315
Location: /home/thamieu/.local/share/flatpak/app/work.openpaper.Paperwork/x86_64/stable/f766b301c2ce30dce580878a0c1d385cbbc7d7206299ed35cd75e44cc0f9d242
Installed size: 197,6 MB
Runtime: org.gnome.Platform/x86_64/3.26
$ flatpak update work.openpaper.Paperwork
Looking for updates...
$
```

Checking on flathub: [1.2.3](https://beta.flathub.org/apps/details/work.openpaper.Paperwork).

According to https://origami.openpaper.work/#/builders/7, last build went almost fine, except a permission issue on paperwork_1.2.4.flatpakref.

**Comment by jflesch** [comment]
The branch shouldn't be 'stable', it should be 'master'. I suggest you uninstall it and reinstall it.

**Comment by jflesch** [comment]
BTW, I haven't updated Paperwork on FlatHub yet. Since they are not show casing applications anymore, I'm considering removing it from FlatHub since it means extra work for me for nothing.

**Comment by jflesch** [comment]
Update is on its way: https://flathub.org/builds/#/builders/2/builds/690

**Comment by jflesch** [comment]
Libpillowfight: https://github.com/openpaperwork/libpillowfight/commit/ae966b721cce84d20965e9fa8cc2f5be67cad2ef

Now I must update the .flatpak files.

**Comment by jflesch** [comment]
https://flathub.org/builds/#/builders/2/builds/728
And done :)
The update is available on FlatHub.

**Comment by mjourdan** [comment]
> ~~Since they are not show casing applications anymore, I'm considering removing it from FlatHub since it means extra work for me for nothing.~~

IIRC hosting on GNOME gitlab could help to avoid this extra work.

BTW, I could update to 1.2.4 using the cli, even if the web page on flathub still indicates 1.2.3. Thanks!
