### ISSUE TITLE
OCR leaves me with a blank page and a couple of black bars

### ISSUE THREAD

**Issue by danielroehrig** [openpaperwork/paperwork#783]
After an upgrade to version 1.2.4, scanning seems to work fine but after the ocr is done, I'm left with just a blank page and a couple of black bars. Every time I issue the "redo ocr" command, it shows me the document before returning to the blank image. I can just turn off OCR and everything works fine. My OS is an Ubuntu 18.04 and my OCR language is German.

Edit: paperwork also cannot figure out the orientation of the document any more and always assumes landscape.

**Comment by danielroehrig** [comment]
Some diagnostics:
`INFO   paperwork.frontend.mainwindow.scan Failed to use OCR tool heuristic for orientation detection: 'KeyError' object has no attribute 'message'`
`INFO   paperwork.frontend.mainwindow  Redoing OCR on 20180613_0737_06 p1
INFO   paperwork.frontend.mainwindow.scan Will use tool 'Tesseract (sh)'`
`WARNING paperwork.frontend.util.jobs   Job OCR:0 took 2208ms and is unstoppable ! (maximum allowed: 500ms)`
Edit: tesseract version: 4.00+git24-0e00fe6-1.2

**Comment by jflesch** [comment]
AFAIK, Tesseract 4.00 is still in beta. Also it is currently not supported by PyOCR (see bug https://github.com/openpaperwork/pyocr/issues/99 ).
I have *no* idea why some distributions (like Debian testing for instance) have already packaged Tesseract 4.

**Comment by jflesch** [comment]
My advise: For now, try to switch back to Tesseract 3.05. Everything should work fine.
